/* 3S — exercise library.
 *
 * GENERATED by tools/build-library.js from the ExerciseAnimatic catalogue. Do not
 * hand-edit: rerun the generator instead, or the next run will overwrite the edit.
 *
 * Every entry is backed by a purchased clip, which is the primary representation.
 * The drawn figure remains the fallback for any exercise whose clip is missing,
 * still loading, or fails to decode — so each entry adopts the closest of the
 * hand-authored pose loops in ARCH below. Those loops are the old library's
 * surviving work and are still tuned by hand.
 *
 *   id      unique slug
 *   name    display name, cleaned of the vendor's delivery tags
 *   pool    'stretch' | 'strength' | 'sweat'   (their folder tree)
 *   groups  slots it can fill in a workout template
 *   equip   [] means anywhere; otherwise every token must be available
 *   tier    1 easiest .. 3 hardest (used for gradual progression)
 *   cue     one short coaching line shown under the name
 *   arch    which pose loop the fallback figure animates
 *   cycle   seconds for one full rep loop (from the archetype unless overridden)
 *   dose    stretch only: target seconds (40 ballistic, 48 flow, 56 held)
 *   frames  resolved from `arch`; the player and the tests read this
 */
/* 3S — exercise library.
 *
 * Each exercise is data only. To add one, append an entry to EX below:
 *   id      unique slug
 *   name    display name
 *   pool    'stretch' | 'strength' | 'sweat'
 *   groups  slots it can fill in a workout template
 *   equip   [] means anywhere; otherwise every token must be available
 *   tier    1 easiest .. 3 hardest (used for gradual progression)
 *   cue     one short coaching line shown under the name
 *   cycle   seconds for one full rep loop
 *   dose    stretch only: target seconds for the move (40 ballistic, 48 flow,
 *           56 held). The generator trims a few seconds to hit 20:00 exactly.
 *   frames  closed keyframe loop; last frame interpolates back to the first
 *   alt     true if the exercise switches sides halfway through the interval
 *   props   fixtures/implements drawn with the figure
 */
(function (global) {
  'use strict';

  function P() {
    var out = {}, i, k, o;
    for (i = 0; i < arguments.length; i++) {
      o = arguments[i];
      for (k in o) out[k] = o[k];
    }
    return out;
  }

  /* ---------- base poses ---------- */

  var STAND = { hip: [120, 118], torso: 90, footL: [112, 178], footR: [128, 178], handL: [112, 118], handR: [128, 118] };
  var NARROW = P(STAND, { hip: [120, 116], footL: [117, 178], footR: [123, 178] });
  var WIDE = P(STAND, { hip: [120, 124], footL: [96, 178], footR: [144, 178] });

  var ARMS_UP = { handL: [112, 34], handR: [128, 34] };
  var ARMS_SIDE = { handL: [86, 92], handR: [154, 92] };
  var ARMS_FWD = { handL: [156, 88], handR: [160, 92] };
  var HANDS_HIP = { handL: [107, 121], handR: [133, 121] };
  var HANDS_CLASP = { handL: [148, 128], handR: [152, 126] };

  /* Squats: the hip travels back as well as down, so the thigh reaches
   * horizontal with the shin vertical rather than the knee shooting forward. */
  var SQUAT_HALF = P(STAND, { hip: [110, 132], torso: 76, footL: [110, 178], footR: [130, 178], handL: [144, 108], handR: [148, 106] });
  var SQUAT_LOW = P(STAND, { hip: [104, 148], torso: 62, footL: [112, 178], footR: [130, 178], handL: [148, 124], handR: [152, 122] });
  var SQUAT_DEEP = P(STAND, { hip: [100, 158], torso: 56, footL: [108, 178], footR: [130, 178], handL: [140, 142], handR: [144, 140], arch: 5 });

  var HINGE_TOP = P(STAND, { hip: [118, 118], torso: 86, handL: [112, 128], handR: [128, 128] });
  var HINGE_LOW = P(STAND, {
    hip: [110, 124], torso: 16, arch: -4,
    footL: [110, 178], footR: [126, 178],
    handL: [146, 148], handR: [150, 146]
  });

  var BENT_OVER = P(STAND, {
    hip: [110, 124], torso: 20, arch: -4,
    footL: [110, 178], footR: [126, 178],
    handL: [148, 150], handR: [152, 152]
  });
  var ROW_PULL = P(BENT_OVER, { handL: [142, 128], handR: [146, 130], elbowL: 1, elbowR: 1 });

  var PLANK_HIGH = { hip: [123, 150], torso: 30, head: -18, footL: [77, 178], footR: [83, 178], handL: [158, 178], handR: [164, 178] };
  var PUSHUP_LOW = P(PLANK_HIGH, { hip: [123, 158], torso: 30 });
  var PLANK_FORE = { hip: [120, 152], torso: 24, head: -14, footL: [74, 178], footR: [80, 178], handL: [166, 178], handR: [172, 178], elbowL: 1, elbowR: 1 };
  var SIDE_PLANK = { hip: [120, 150], torso: 20, head: -12, footL: [74, 176], footR: [80, 178], handL: [148, 96], handR: [168, 178], elbowR: 1 };

  var TUCK = { hip: [116, 156], torso: 20, head: -12, footL: [106, 178], footR: [114, 178], handL: [156, 178], handR: [162, 178] };
  var JUMP_UP = { hip: [120, 102], torso: 92, footL: [113, 164], footR: [127, 162], handL: [110, 28], handR: [130, 28] };

  /* Lying on the back, head to the right. Sits high enough that the head circle
   * rests on the ground line instead of sinking through it. */
  var LIE_BACK = { hip: [116, 166], torso: -4, head: 4, footL: [104, 178], footR: [110, 178], handL: [130, 174], handR: [134, 174], kneeL: -1, kneeR: -1 };
  var BRIDGE_UP = P(LIE_BACK, { hip: [122, 148], torso: -16, head: 16, footL: [84, 178], footR: [90, 178], handL: [136, 174], handR: [140, 174] });
  var BRIDGE_DOWN = P(LIE_BACK, { hip: [120, 166], torso: -4, head: 4, footL: [86, 178], footR: [92, 178], handL: [132, 174], handR: [136, 174] });

  var HANG = { hip: [120, 112], torso: 90, footL: [116, 172], footR: [124, 172], handL: [112, 26], handR: [128, 26] };
  var HANG_TOP = P(HANG, { hip: [120, 86], footL: [104, 138], footR: [110, 134], kneeL: -1, kneeR: -1 });

  var LUNGE_DOWN = { hip: [116, 142], torso: 87, footL: [84, 178], footR: [152, 178], handL: [106, 142], handR: [126, 142] };
  var LUNGE_SHALLOW = P(LUNGE_DOWN, { hip: [117, 128], footR: [148, 178], footL: [90, 178] });
  var LUNGE_BACK_DOWN = { hip: [118, 142], torso: 88, footL: [152, 178], footR: [86, 178], handL: [108, 142], handR: [128, 142] };

  var PRESS_RACK = P(STAND, { handL: [104, 86], handR: [136, 86], elbowL: -1, elbowR: -1 });
  var PRESS_TOP = P(STAND, ARMS_UP);

  var KNEE_R = P(NARROW, { footR: [138, 126], handR: [104, 104], handL: [138, 112], kneeR: 1 });
  var KNEE_L = P(NARROW, { footL: [138, 126], handL: [104, 104], handR: [138, 112], kneeL: 1 });

  var JJ_IN = P(NARROW, { handL: [108, 116], handR: [132, 116] });
  var JJ_OUT = P(STAND, { hip: [120, 126], footL: [92, 178], footR: [148, 178], handL: [92, 52], handR: [148, 52] });

  var QUAD_ALL4 = { hip: [104, 146], torso: 4, head: -4, footL: [78, 178], footR: [84, 178], handL: [150, 178], handR: [156, 178] };
  var CAT = P(QUAD_ALL4, { arch: 13, head: -32, hip: [104, 142] });
  var COW = P(QUAD_ALL4, { arch: -9, head: 20, hip: [104, 150] });

  var DOWN_DOG = { hip: [104, 118], torso: 2, head: -22, arch: -3, footL: [72, 178], footR: [78, 178], handL: [150, 178], handR: [156, 178] };
  var COBRA = { hip: [96, 172], torso: 34, head: 16, arch: -12, footL: [58, 176], footR: [64, 178], handL: [134, 178], handR: [140, 178], kneeL: -1, kneeR: -1 };
  var CHILD = { hip: [90, 164], torso: 8, head: -14, arch: 8, footL: [70, 178], footR: [76, 178], handL: [162, 178], handR: [168, 178] };

  var SEATED_FOLD = { hip: [104, 172], torso: 40, head: -18, arch: 6, footL: [162, 176], footR: [168, 178], handL: [156, 156], handR: [162, 158], kneeL: -1, kneeR: -1 };

  var BOX_GUARD = P(NARROW, { hip: [120, 122], torso: 86, footL: [104, 178], footR: [134, 178], handL: [138, 100], handR: [134, 108] });

  /* ---------- pose loops the fallback figure animates ---------- */

  var ARCH = {
    'ankle-circles': { cycle: 3.4, alt: true, frames: [P(NARROW, HANDS_HIP, { footR: [146, 148] }), P(NARROW, HANDS_HIP, { footR: [154, 158] }), P(NARROW, HANDS_HIP, { footR: [142, 162] })] },
    'arm-circles': { cycle: 3.2, frames: [P(STAND, ARMS_SIDE), P(STAND, ARMS_UP), P(STAND, { handL: [96, 132], handR: [144, 132] })] },
    'arm-swings': { cycle: 2.6, frames: [P(STAND, { handL: [148, 108], handR: [152, 116] }), P(STAND, { handL: [88, 100], handR: [154, 104] })] },
    'band-pull-apart': { cycle: 2.6, frames: [P(NARROW, { handL: [154, 90], handR: [158, 94] }), P(NARROW, { handL: [92, 96], handR: [156, 92] })] },
    'bb-bench': { cycle: 3.2, props: ['bench', 'barbell'], frames: [P(LIE_BACK, { hip: [116, 142], torso: -6, head: 6, footL: [58, 178], footR: [64, 178], handL: [148, 130], handR: [154, 132], elbowL: -1, elbowR: -1 }), P(LIE_BACK, { hip: [116, 142], torso: -6, head: 6, footL: [58, 178], footR: [64, 178], handL: [154, 96], handR: [160, 98] })] },
    'bb-deadlift': { cycle: 3.8, props: ['barbell'], frames: [P(HINGE_TOP, { handL: [112, 128], handR: [128, 128] }), P(STAND, { hip: [108, 134], torso: 34, arch: -4, handL: [140, 168], handR: [146, 170], footL: [112, 178], footR: [126, 178] })] },
    'bb-squat': { cycle: 3.6, props: ['barbell'], frames: [P(STAND, { handL: [104, 84], handR: [136, 86], elbowL: -1, elbowR: -1 }), P(SQUAT_LOW, { handL: [112, 112], handR: [142, 114], elbowL: -1, elbowR: -1 })] },
    'bear-crawl': { cycle: 1.6, frames: [P(QUAD_ALL4, { hip: [108, 140], footL: [80, 172], footR: [86, 170] }), P(QUAD_ALL4, { hip: [108, 140], footL: [76, 162], footR: [86, 170], handR: [162, 168] })] },
    'bird-dog': { cycle: 5, alt: true, frames: [QUAD_ALL4, P(QUAD_ALL4, { footL: [46, 138], handR: [176, 132], arch: -4, head: 2 })] },
    'burpee': { cycle: 3, frames: [P(JUMP_UP, { hip: [120, 104] }), TUCK, PLANK_HIGH, PUSHUP_LOW, PLANK_HIGH, TUCK] },
    'butt-kicks': { cycle: 0.8, frames: [P(NARROW, { footR: [98, 123], handR: [104, 106], handL: [136, 112], kneeR: 1 }), P(NARROW, { footL: [98, 123], handL: [104, 106], handR: [136, 112], kneeL: 1 })] },
    'calf-raise': { cycle: 2.4, frames: [P(NARROW, HANDS_HIP), P(NARROW, HANDS_HIP, { hip: [120, 104], footL: [117, 172], footR: [123, 172] })] },
    'calf-stretch-step': { cycle: 5, alt: true, frames: [P(STAND, HANDS_HIP, { hip: [122, 130], torso: 88, footR: [146, 178], footL: [86, 178] }), P(STAND, HANDS_HIP, { hip: [124, 132], torso: 88, footR: [148, 178], footL: [84, 178] })] },
    'cat-cow': { cycle: 5, frames: [CAT, COW] },
    'chair-dip': { cycle: 3, props: ['chair'], frames: [P(STAND, { hip: [140, 148], torso: 84, footL: [86, 178], footR: [94, 178], handL: [168, 140], handR: [174, 140], kneeL: 1, kneeR: 1, elbowL: -1, elbowR: -1 }), P(STAND, { hip: [138, 164], torso: 84, footL: [86, 178], footR: [94, 178], handL: [168, 140], handR: [174, 140], kneeL: 1, kneeR: 1, elbowL: -1, elbowR: -1 })] },
    'cobra-hold': { cycle: 5, frames: [COBRA, P(COBRA, { torso: 40, head: 18, arch: -14 })] },
    'cross-body-shoulder': { cycle: 5, alt: true, frames: [P(STAND, { handR: [94, 100], handL: [102, 106] }), P(STAND, { handR: [88, 96], handL: [98, 102] })] },
    'cross-jacks': { cycle: 1.2, frames: [P(JJ_OUT, { footL: [98, 178], footR: [142, 178] }), P(NARROW, { hip: [120, 120], footL: [126, 178], footR: [114, 178], handL: [142, 108], handR: [100, 106] })] },
    'crunch-reach': { cycle: 3, frames: [P(LIE_BACK, { footL: [86, 178], footR: [92, 178], handL: [150, 168], handR: [156, 170] }), P(LIE_BACK, { torso: 22, head: -10, arch: 8, footL: [86, 178], footR: [92, 178], handL: [172, 150], handR: [178, 152] })] },
    'db-carry': { cycle: 2, props: ['dumbbells'], frames: [P(NARROW, { handL: [110, 122], handR: [130, 122] }), P(NARROW, { hip: [120, 114], handL: [110, 120], handR: [130, 120] })] },
    'db-curl': { cycle: 2.6, props: ['dumbbells'], frames: [P(STAND, { handL: [110, 122], handR: [130, 122] }), P(STAND, { handL: [108, 88], handR: [134, 88], elbowL: -1, elbowR: -1 })] },
    'db-lateral-raise': { cycle: 2.8, props: ['dumbbells'], frames: [P(STAND, { handL: [112, 120], handR: [128, 120] }), P(STAND, ARMS_SIDE)] },
    'db-overhead-tri': { cycle: 2.8, props: ['dumbbell'], frames: [P(STAND, { handL: [120, 40], handR: [124, 38] }), P(STAND, { handL: [140, 82], handR: [144, 80], elbowL: 1, elbowR: 1 })] },
    'db-renegade-row': { cycle: 3.4, alt: true, props: ['dumbbells'], frames: [PLANK_HIGH, P(PLANK_HIGH, { handR: [150, 152], elbowR: 1 })] },
    'db-row': { cycle: 3, props: ['dumbbells'], frames: [BENT_OVER, ROW_PULL] },
    'db-shoulder-press': { cycle: 3, props: ['dumbbells'], frames: [PRESS_RACK, PRESS_TOP] },
    'db-thruster': { cycle: 3.4, props: ['dumbbells'], frames: [PRESS_RACK, P(SQUAT_LOW, { handL: [116, 106], handR: [132, 108], elbowL: -1, elbowR: -1 }), PRESS_TOP] },
    'dd-hold': { cycle: 5, frames: [DOWN_DOG, P(DOWN_DOG, { hip: [104, 115], head: -25 })] },
    'diamond-pushup': { cycle: 3, frames: [P(PLANK_HIGH, { handL: [160, 178], handR: [164, 178] }), P(PUSHUP_LOW, { handL: [160, 178], handR: [164, 178] })] },
    'down-dog-cobra': { cycle: 6, frames: [DOWN_DOG, PLANK_HIGH, COBRA, PLANK_HIGH] },
    'fast-feet': { cycle: 0.5, frames: [P(SQUAT_HALF, { footL: [108, 174], footR: [130, 178], handL: [148, 112], handR: [152, 116] }), P(SQUAT_HALF, { footL: [110, 178], footR: [132, 174], handL: [148, 112], handR: [152, 116] })] },
    'frog-rocks': { cycle: 4.5, frames: [P(QUAD_ALL4, { hip: [110, 150], footL: [72, 178], footR: [80, 178] }), P(QUAD_ALL4, { hip: [88, 156], footL: [62, 178], footR: [70, 178], arch: 5, head: -10 })] },
    'glute-bridge': { cycle: 3, frames: [BRIDGE_DOWN, BRIDGE_UP] },
    'glute-bridge-mob': { cycle: 4, frames: [BRIDGE_DOWN, BRIDGE_UP] },
    'good-morning': { cycle: 3.4, frames: [P(HINGE_TOP, { handL: [126, 96], handR: [130, 100], elbowL: 1, elbowR: 1 }), P(HINGE_LOW, { handL: [150, 122], handR: [154, 126], elbowL: 1, elbowR: 1 })] },
    'hang-knee-raise': { cycle: 3.4, props: ['pullbar'], frames: [HANG, P(HANG, { footL: [140, 128], footR: [146, 124], arch: 6, kneeL: 1, kneeR: 1 })] },
    'high-knees': { cycle: 0.8, frames: [KNEE_R, KNEE_L] },
    'hip-circles': { cycle: 4.5, alt: true, frames: [P(NARROW, HANDS_HIP, { footR: [140, 128] }), P(NARROW, HANDS_HIP, { footR: [152, 146], kneeR: 1 }), P(NARROW, HANDS_HIP, { footR: [126, 150] })] },
    'jump-rope': { cycle: 0.7, frames: [P(NARROW, { handL: [102, 110], handR: [138, 110], elbowL: 1, elbowR: 1 }), P(NARROW, { hip: [120, 108], footL: [117, 172], footR: [123, 172], handL: [102, 104], handR: [138, 104], elbowL: 1, elbowR: 1 })] },
    'jumping-jacks': { cycle: 1.1, frames: [JJ_IN, JJ_OUT] },
    'knee-hugs': { cycle: 3.6, frames: [P(NARROW, { footR: [136, 122], handR: [140, 128], handL: [134, 120] }), STAND, P(NARROW, { footL: [136, 122], handL: [140, 128], handR: [134, 120] })] },
    'knee-strikes': { cycle: 1.2, frames: [P(BOX_GUARD, { handL: [140, 92], handR: [136, 98] }), P(BOX_GUARD, { footR: [140, 124], handL: [148, 128], handR: [144, 134], kneeR: 1 })] },
    'leg-swings-fb': { cycle: 2.6, alt: true, frames: [P(NARROW, HANDS_HIP, { footR: [166, 142] }), P(NARROW, HANDS_HIP, { footR: [92, 158], kneeR: -1 })] },
    'lunge-reach': { cycle: 5, alt: true, frames: [P(LUNGE_DOWN, { handL: [112, 40], handR: [126, 38], torso: 92 }), P(STAND, ARMS_UP)] },
    'mountain-climbers': { cycle: 0.9, frames: [P(PLANK_HIGH, { footR: [132, 166], kneeR: 1 }), P(PLANK_HIGH, { footL: [126, 164], footR: [83, 178], kneeL: 1 })] },
    'neck-side': { cycle: 5, alt: true, frames: [P(STAND, HANDS_HIP, { head: -28, torso: 88 }), P(STAND, { head: -34, torso: 88, handL: [110, 120], handR: [126, 66] })] },
    'pigeon': { cycle: 5, alt: true, frames: [{ hip: [112, 164], torso: 34, head: -10, arch: 2, footR: [150, 172], footL: [62, 176], handL: [162, 176], handR: [168, 178], kneeR: -1, kneeL: -1 }, { hip: [112, 166], torso: 26, head: -14, arch: 4, footR: [150, 172], footL: [62, 176], handL: [162, 176], handR: [168, 178], kneeR: -1, kneeL: -1 }] },
    'pike-pushup': { cycle: 3.2, frames: [DOWN_DOG, P(DOWN_DOG, { hip: [104, 124], handL: [150, 178], handR: [156, 178], head: -30, torso: -4 })] },
    'plank': { cycle: 5, frames: [PLANK_FORE, P(PLANK_FORE, { hip: [120, 150] })] },
    'prone-y-raise': { cycle: 3.4, frames: [{ hip: [112, 172], torso: 4, head: 6, footL: [66, 178], footR: [72, 178], handL: [178, 176], handR: [184, 174] }, { hip: [112, 171], torso: 6, head: 12, arch: -6, footL: [66, 178], footR: [72, 178], handL: [180, 154], handR: [186, 150] }] },
    'pull-up': { cycle: 3.4, props: ['pullbar'], frames: [HANG, HANG_TOP] },
    'punch-overhead': { cycle: 0.9, frames: [P(NARROW, { handL: [112, 40], handR: [130, 92] }), P(NARROW, { handL: [110, 92], handR: [128, 38] })] },
    'pushup': { cycle: 3, frames: [PLANK_HIGH, PUSHUP_LOW] },
    'quad-pull': { cycle: 4, alt: true, frames: [P(NARROW, { footR: [98, 123], handR: [102, 132], handL: [124, 116], kneeR: 1 }), P(NARROW, { footR: [96, 118], handR: [100, 128], handL: [124, 116], kneeR: 1 })] },
    'reverse-lunge': { cycle: 3.2, alt: true, frames: [P(STAND, HANDS_HIP), P(LUNGE_BACK_DOWN, HANDS_HIP)] },
    'seated-fold': { cycle: 5, frames: [P(SEATED_FOLD, { torso: 58, arch: 0, handL: [148, 140], handR: [154, 142] }), SEATED_FOLD] },
    'shadow-box': { cycle: 1, frames: [BOX_GUARD, P(BOX_GUARD, { handR: [164, 92], torso: 84 }), BOX_GUARD, P(BOX_GUARD, { handL: [166, 96], torso: 80 })] },
    'shoulder-rolls': { cycle: 3.4, frames: [P(STAND, { handL: [110, 120], handR: [130, 120] }), P(STAND, { handL: [108, 110], handR: [132, 110] }), P(STAND, { handL: [114, 108], handR: [126, 108], elbowL: 1, elbowR: 1 })] },
    'side-bend': { cycle: 4, alt: true, frames: [P(WIDE, { torso: 74, handL: [148, 52], handR: [154, 60], head: 8 }), P(WIDE, ARMS_UP), P(WIDE, { torso: 104, handL: [88, 56], handR: [96, 50], head: -8 })] },
    'side-plank': { cycle: 5, alt: true, frames: [SIDE_PLANK, P(SIDE_PLANK, { hip: [120, 146] })] },
    'skater-hops': { cycle: 1.4, frames: [{ hip: [138, 134], torso: 78, footR: [146, 178], footL: [108, 162], handL: [148, 118], handR: [116, 128], kneeL: -1 }, { hip: [102, 134], torso: 100, footL: [94, 178], footR: [132, 162], handR: [92, 118], handL: [124, 128], kneeR: -1 }] },
    'split-jump': { cycle: 1.6, frames: [P(LUNGE_DOWN, { handL: [104, 110], handR: [140, 108] }), P(JUMP_UP, { hip: [120, 110], footL: [96, 166], footR: [146, 160] }), P(LUNGE_BACK_DOWN, { handL: [140, 108], handR: [104, 110] })] },
    'split-squat': { cycle: 3, alt: true, frames: [P(LUNGE_SHALLOW, HANDS_HIP), P(LUNGE_DOWN, HANDS_HIP)] },
    'sprint-place': { cycle: 0.6, frames: [P(NARROW, { hip: [120, 114], torso: 84, footR: [140, 132], footL: [104, 176], handR: [100, 100], handL: [142, 116], kneeR: 1 }), P(NARROW, { hip: [120, 114], torso: 84, footL: [140, 132], footR: [104, 176], handL: [100, 100], handR: [142, 116], kneeL: 1 })] },
    'squat': { cycle: 3, frames: [P(STAND, HANDS_CLASP), SQUAT_LOW] },
    'squat-jump': { cycle: 1.6, frames: [SQUAT_LOW, P(JUMP_UP, { handL: [104, 96], handR: [140, 92] })] },
    'standing-ham-reach': { cycle: 5, alt: true, frames: [P(STAND, { hip: [108, 132], torso: 46, footR: [152, 172], footL: [100, 178], handL: [152, 148], handR: [158, 152] }), P(STAND, { hip: [106, 130], torso: 38, footR: [152, 172], footL: [98, 178], handL: [154, 158], handR: [160, 162] })] },
    'star-jump': { cycle: 1.8, frames: [P(SQUAT_HALF, { handL: [128, 130], handR: [132, 132] }), P(JUMP_UP, { hip: [120, 106], footL: [88, 160], footR: [152, 158], handL: [84, 62], handR: [156, 60] })] },
    'supine-twist': { cycle: 5, alt: true, frames: [P(LIE_BACK, { torso: -4, arch: 4, footR: [150, 158], footL: [146, 162], handL: [132, 176], handR: [186, 166], kneeR: 1, kneeL: 1 }), P(LIE_BACK, { torso: -4, arch: 6, footR: [152, 164], footL: [148, 168], handL: [132, 176], handR: [186, 164], kneeR: 1, kneeL: 1 })] },
    'toe-taps': { cycle: 0.8, props: ['chair'], frames: [P(NARROW, { footR: [152, 142], handL: [110, 112], handR: [132, 110], kneeR: 1 }), P(NARROW, { footL: [152, 142], handR: [110, 112], handL: [132, 110], kneeL: 1 })] },
    'torso-twist': { cycle: 3, frames: [P(WIDE, { handL: [92, 104], handR: [146, 116] }), P(WIDE, { handL: [148, 112], handR: [154, 104] })] },
    'wall-sit': { cycle: 5, props: ['wall'], frames: [P(STAND, { hip: [54, 147], torso: 90, footL: [80, 178], footR: [88, 178], handL: [76, 142], handR: [84, 142] }), P(STAND, { hip: [54, 149], torso: 90, footL: [80, 178], footR: [88, 178], handL: [76, 144], handR: [84, 144] })] },
    'wrist-circles': { cycle: 3, frames: [P(STAND, { handL: [144, 108], handR: [148, 112], elbowL: 1, elbowR: 1 }), P(STAND, { handL: [148, 94], handR: [152, 98], elbowL: 1, elbowR: 1 }), P(STAND, { handL: [138, 96], handR: [142, 100], elbowL: 1, elbowR: 1 })] }
  };

  /* ---------- library ---------- */

  var RAW = [
    { id: '3-leg-dog-pose', name: '3 Leg Dog Pose', pool: 'stretch', groups: ['ankles', 'hams', 'hips', 'shoulders'], equip: [], tier: 1, arch: 'ankle-circles', cue: 'Engage your core to maintain balance and stability throughout the movement', dose: 56 },
    { id: 'alternate-sprinter-lunge', name: 'Alternate Sprinter Lunge', pool: 'stretch', groups: ['ankles', 'hams', 'hips'], equip: [], tier: 1, arch: 'lunge-reach', cue: 'Keep your core engaged to maintain balance and stability throughout the', dose: 48 },
    { id: 'alternating-leg-downward-dog', name: 'Alternating Leg Downward Dog', pool: 'stretch', groups: ['ankles', 'hams', 'hips', 'shoulders'], equip: [], tier: 1, arch: 'down-dog-cobra', cue: 'Keep your core engaged to maintain stability and balance throughout the', dose: 48 },
    { id: 'ankle-dorsal-flexion', name: 'Ankle - Dorsal Flexion', pool: 'stretch', groups: ['ankles'], equip: [], tier: 1, arch: 'ankle-circles', cue: 'Keep your core engaged to maintain balance and stability throughout the', dose: 48 },
    { id: 'ankle-plantar-flexion', name: 'Ankle - Plantar Flexion', pool: 'stretch', groups: ['ankles'], equip: [], tier: 1, arch: 'ankle-circles', cue: 'Keep your knees slightly bent to reduce strain on your joints and enhance', dose: 48 },
    { id: 'ankle-circles', name: 'Ankle Circles', pool: 'stretch', groups: ['ankles'], equip: [], tier: 1, arch: 'ankle-circles', cue: 'Keep your core engaged to maintain balance and stability throughout the', dose: 48 },
    { id: 'calf-stretch-foot-on-wall', name: 'Calf Stretch Foot on Wall', pool: 'stretch', groups: ['ankles'], equip: ['wall'], tier: 1, arch: 'calf-stretch-step', cue: 'Back leg straight, press the heel into the floor', dose: 48 },
    { id: 'calf-stretch-from-wall-to-floor', name: 'Calf Stretch from Wall to Floor', pool: 'stretch', groups: ['ankles'], equip: ['wall'], tier: 1, arch: 'calf-stretch-step', cue: 'Back leg straight, press the heel into the floor', dose: 48 },
    { id: 'calf-stretch-on-step', name: 'Calf Stretch on Step', pool: 'stretch', groups: ['ankles'], equip: ['bench'], tier: 1, arch: 'calf-stretch-step', cue: 'Back leg straight, press the heel into the floor', dose: 48 },
    { id: 'downward-dog-toe-to-heel', name: 'Downward Dog Toe to Heel', pool: 'stretch', groups: ['ankles', 'hams'], equip: [], tier: 1, arch: 'down-dog-cobra', cue: 'Press the hips up, then open the chest', dose: 48 },
    { id: 'downward-dog-with-fingers-facing-feet', name: 'Downward Dog with Fingers Facing Feet', pool: 'stretch', groups: ['ankles', 'hams'], equip: [], tier: 1, arch: 'down-dog-cobra', cue: 'Press the hips up, then open the chest', dose: 48 },
    { id: 'seated-single-leg-toe-touch-hamstring-stretc', name: 'Seated Single Leg Toe Touch Hamstring Stretch', pool: 'stretch', groups: ['ankles', 'hams'], equip: [], tier: 1, arch: 'seated-fold', cue: 'Long spine first, then fold', dose: 56 },
    { id: 'seated-toe-touch-hamstrings-stretch', name: 'Seated Toe Touch Hamstrings Stretch', pool: 'stretch', groups: ['ankles', 'hams'], equip: [], tier: 1, arch: 'seated-fold', cue: 'Long spine first, then fold', dose: 56 },
    { id: 'archer-stepback', name: 'Archer Stepback', pool: 'stretch', groups: ['hams', 'hips', 'shoulders', 'spine'], equip: [], tier: 1, arch: 'standing-ham-reach', cue: 'Engage your core to maintain balance and stability throughout the exercise', dose: 48 },
    { id: 'back-forward-leg-swings', name: 'Back Forward Leg Swings', pool: 'stretch', groups: ['hams', 'hips', 'spine'], equip: [], tier: 1, arch: 'leg-swings-fb', cue: 'Focus on maintaining a steady rhythm to ensure controlled movements', dose: 48 },
    { id: 'half-monkey-pose', name: 'Half Monkey Pose', pool: 'stretch', groups: ['hams'], equip: [], tier: 1, arch: 'standing-ham-reach', cue: 'Front leg straight, hinge and reach for the toes', dose: 56 },
    { id: 'monkey-pose', name: 'Monkey Pose', pool: 'stretch', groups: ['hams'], equip: [], tier: 1, arch: 'standing-ham-reach', cue: 'Front leg straight, hinge and reach for the toes', dose: 56 },
    { id: 'pyramid-prayer', name: 'Pyramid Prayer', pool: 'stretch', groups: ['hams'], equip: [], tier: 1, arch: 'standing-ham-reach', cue: 'Front leg straight, hinge and reach for the toes', dose: 48 },
    { id: 'resistance-band-glute-bridge', name: 'Resistance Band Glute Bridge', pool: 'stretch', groups: ['hams', 'hips', 'spine'], equip: ['band'], tier: 1, arch: 'glute-bridge-mob', cue: 'Avoid arching your lower back; keep a straight line from your shoulders to', dose: 48 },
    { id: 'resistance-band-glute-bridge-abduction', name: 'Resistance Band Glute Bridge Abduction', pool: 'stretch', groups: ['hams', 'hips', 'spine'], equip: ['band'], tier: 1, arch: 'glute-bridge-mob', cue: 'Avoid arching your lower back; keep a straight line from your shoulders to', dose: 48 },
    { id: 'resistance-band-glute-bridge-version2', name: 'Resistance Band Glute Bridge Version2', pool: 'stretch', groups: ['hams', 'hips', 'spine'], equip: ['band'], tier: 1, arch: 'glute-bridge-mob', cue: 'Avoid arching your lower back; keep a straight line from your shoulders to', dose: 48 },
    { id: 'revolved-head-to-knee', name: 'Revolved Head to Knee', pool: 'stretch', groups: ['hams'], equip: [], tier: 1, arch: 'standing-ham-reach', cue: 'Front leg straight, hinge and reach for the toes', dose: 48 },
    { id: 'runners-lunge', name: 'Runners Lunge', pool: 'stretch', groups: ['hams', 'hips'], equip: [], tier: 1, arch: 'lunge-reach', cue: 'Sink the hips, reach tall', dose: 48 },
    { id: 'standing-straight-leg-hamstring-stretch', name: 'Standing Straight-leg Hamstring Stretch', pool: 'stretch', groups: ['hams'], equip: [], tier: 1, arch: 'standing-ham-reach', cue: 'Front leg straight, hinge and reach for the toes', dose: 48 },
    { id: '3-leg-chaturanga-pose', name: '3 Leg Chaturanga Pose', pool: 'stretch', groups: ['hips', 'shoulders'], equip: [], tier: 1, arch: 'hip-circles', cue: 'Engage your core to maintain balance and stability throughout the movement', dose: 56 },
    { id: '90-to-90-stretch', name: '90 to 90 Stretch', pool: 'stretch', groups: ['hips'], equip: [], tier: 1, arch: 'hip-circles', cue: 'Keep your back straight as you lean forward to maximize the stretch and avoid', dose: 48 },
    { id: 'ab-stretch', name: 'Ab Stretch', pool: 'stretch', groups: ['hips', 'spine'], equip: [], tier: 1, arch: 'hip-circles', cue: 'Keep your shoulders relaxed and avoid hunching them up towards your ears', dose: 48 },
    { id: 'adductor-dynamic-stretch', name: 'Adductor Dynamic Stretch', pool: 'stretch', groups: ['hips'], equip: [], tier: 1, arch: 'frog-rocks', cue: 'Rock back into the hips, easy breath', dose: 40 },
    { id: 'adductor-stretch', name: 'Adductor Stretch', pool: 'stretch', groups: ['hips'], equip: [], tier: 1, arch: 'frog-rocks', cue: 'Keep your core engaged to maintain stability and control throughout the', dose: 48 },
    { id: 'adductor-stretch-side-standing', name: 'Adductor Stretch Side Standing', pool: 'stretch', groups: ['hips'], equip: [], tier: 1, arch: 'frog-rocks', cue: 'Rock back into the hips, easy breath', dose: 48 },
    { id: 'all-fours-quad-stretch', name: 'All Fours Quad Stretch', pool: 'stretch', groups: ['hips'], equip: [], tier: 1, arch: 'quad-pull', cue: 'Keep your core engaged to maintain balance and stability throughout the', dose: 48 },
    { id: 'bulgarian-split-squat-stretch', name: 'Bulgarian Split Squat Stretch', pool: 'stretch', groups: ['hips'], equip: [], tier: 1, arch: 'lunge-reach', cue: 'Sink the hips, reach tall', dose: 48 },
    { id: 'double-pigeon-pose', name: 'Double Pigeon Pose', pool: 'stretch', groups: ['hips'], equip: [], tier: 1, arch: 'pigeon', cue: 'Front shin across, sink the hips down', dose: 56 },
    { id: 'happy-baby', name: 'Happy Baby', pool: 'stretch', groups: ['hips'], equip: [], tier: 1, arch: 'hip-circles', cue: 'Knee up, draw a big circle', dose: 48 },
    { id: 'lying-bent-knee-cross-glutes-stretch', name: 'Lying Bent Knee Cross Glutes Stretch', pool: 'stretch', groups: ['hips'], equip: [], tier: 1, arch: 'hip-circles', cue: 'Knee up, draw a big circle', dose: 56 },
    { id: 'pigeon-glutes-stretch', name: 'Pigeon Glutes Stretch', pool: 'stretch', groups: ['hips'], equip: [], tier: 1, arch: 'pigeon', cue: 'Front shin across, sink the hips down', dose: 48 },
    { id: 'pigeon-pose', name: 'Pigeon Pose', pool: 'stretch', groups: ['hips'], equip: [], tier: 1, arch: 'pigeon', cue: 'Front shin across, sink the hips down', dose: 56 },
    { id: 'reclining-pigeon-pose', name: 'Reclining Pigeon Pose', pool: 'stretch', groups: ['hips'], equip: [], tier: 1, arch: 'pigeon', cue: 'Front shin across, sink the hips down', dose: 56 },
    { id: 'resistance-band-upper-body-dead-bug', name: 'Resistance Band Upper Body Dead Bug', pool: 'stretch', groups: ['hips', 'spine'], equip: ['band'], tier: 1, arch: 'bird-dog', cue: 'Exhale as you lower your leg and inhale as you return it to the starting', dose: 48 },
    { id: 'standing-quadriceps-stretch', name: 'Standing Quadriceps Stretch', pool: 'stretch', groups: ['hips'], equip: [], tier: 1, arch: 'quad-pull', cue: 'Heel to glute, knee points down', dose: 48 },
    { id: '5-sec-fist-against-chin', name: '5 Sec Fist Against Chin', pool: 'stretch', groups: ['shoulders'], equip: [], tier: 1, arch: 'arm-circles', cue: 'Keep your jaw relaxed, avoiding clenching your teeth', dose: 48 },
    { id: 'above-head-chest-stretch', name: 'Above Head Chest Stretch', pool: 'stretch', groups: ['shoulders', 'spine'], equip: [], tier: 1, arch: 'arm-circles', cue: 'Keep your shoulders relaxed and avoid hunching them up towards your ears', dose: 48 },
    { id: 'across-chest-shoulder-stretch', name: 'Across Chest Shoulder Stretch', pool: 'stretch', groups: ['shoulders'], equip: [], tier: 1, arch: 'arm-circles', cue: 'Reach long, shoulders loose', dose: 48 },
    { id: 'armless-prayer-stretch', name: 'Armless Prayer Stretch', pool: 'stretch', groups: ['shoulders', 'spine'], equip: [], tier: 1, arch: 'arm-circles', cue: 'Engage your core to maintain stability and support your lower back throughout', dose: 48 },
    { id: 'arms-behind-back-chest-stretch', name: 'Arms Behind Back Chest Stretch', pool: 'stretch', groups: ['shoulders', 'spine'], equip: [], tier: 1, arch: 'arm-circles', cue: 'Reach long, shoulders loose', dose: 48 },
    { id: 'arms-wide-chest-stretch', name: 'Arms Wide Chest Stretch', pool: 'stretch', groups: ['shoulders'], equip: [], tier: 1, arch: 'arm-circles', cue: 'Reach long, shoulders loose', dose: 48 },
    { id: 'back-and-shoulders-stretch', name: 'Back and Shoulders Stretch', pool: 'stretch', groups: ['shoulders', 'spine'], equip: [], tier: 1, arch: 'arm-circles', cue: 'Keep your core engaged to maintain balance and proper posture throughout the', dose: 48 },
    { id: 'backward-forward-turn-to-side-neck-stretch', name: 'Backward Forward Turn to Side Neck Stretch', pool: 'stretch', groups: ['shoulders', 'spine'], equip: [], tier: 1, arch: 'neck-side', cue: 'Perform the movements slowly and gently to avoid straining your neck muscles', dose: 48 },
    { id: 'band-warm-up-shoulder-stretch', name: 'Band Warm Up Shoulder Stretch', pool: 'stretch', groups: ['shoulders', 'spine'], equip: ['band'], tier: 1, arch: 'arm-circles', cue: 'Keep your arms straight but not locked to avoid joint strain', dose: 48 },
    { id: 'both-arms-behind-on-wall-biceps-stretch', name: 'Both Arms Behind on Wall Biceps Stretch', pool: 'stretch', groups: ['shoulders'], equip: ['wall'], tier: 1, arch: 'cross-body-shoulder', cue: 'Straight arm across the chest, hug it in', dose: 48 },
    { id: 'child-pose-arms-extended-left-right', name: 'Child Pose Arms Extended Left Right', pool: 'stretch', groups: ['shoulders', 'spine'], equip: [], tier: 1, arch: 'seated-fold', cue: 'Long spine first, then fold', dose: 56 },
    { id: 'child-pose-arms-on-side', name: 'Child Pose Arms on Side', pool: 'stretch', groups: ['shoulders', 'spine'], equip: [], tier: 1, arch: 'seated-fold', cue: 'Long spine first, then fold', dose: 56 },
    { id: 'cross-body-elbow-pull-shoulder-stretch', name: 'Cross Body Elbow Pull Shoulder Stretch', pool: 'stretch', groups: ['shoulders'], equip: [], tier: 1, arch: 'arm-swings', cue: 'Wrap then open wide', dose: 48 },
    { id: 'cross-body-shoulder-stretch', name: 'Cross Body Shoulder Stretch', pool: 'stretch', groups: ['shoulders'], equip: [], tier: 1, arch: 'arm-swings', cue: 'Wrap then open wide', dose: 48 },
    { id: 'eagle-arms-chin-into-chest', name: 'Eagle Arms Chin Into Chest', pool: 'stretch', groups: ['shoulders'], equip: [], tier: 1, arch: 'arm-circles', cue: 'Reach long, shoulders loose', dose: 48 },
    { id: 'easy-pose-neck-stretch', name: 'Easy Pose Neck Stretch', pool: 'stretch', groups: ['shoulders'], equip: [], tier: 1, arch: 'neck-side', cue: 'Ear toward the shoulder, no shrugging', dose: 56 },
    { id: 'forearms-pull-with-opposite-hand-stretch', name: 'Forearms Pull with Opposite Hand Stretch', pool: 'stretch', groups: ['shoulders'], equip: [], tier: 1, arch: 'cross-body-shoulder', cue: 'Straight arm across the chest, hug it in', dose: 48 },
    { id: 'forearms-stretch-on-wall', name: 'Forearms Stretch on Wall', pool: 'stretch', groups: ['shoulders'], equip: ['wall'], tier: 1, arch: 'cross-body-shoulder', cue: 'Straight arm across the chest, hug it in', dose: 48 },
    { id: 'forearms-stretch-on-wall-fingers-facing-down', name: 'Forearms Stretch on Wall Fingers Facing Down', pool: 'stretch', groups: ['shoulders'], equip: ['wall'], tier: 1, arch: 'cross-body-shoulder', cue: 'Straight arm across the chest, hug it in', dose: 48 },
    { id: 'gate-pose-arm-extended-on-side', name: 'Gate Pose Arm Extended on Side', pool: 'stretch', groups: ['shoulders'], equip: [], tier: 1, arch: 'arm-circles', cue: 'Reach long, shoulders loose', dose: 56 },
    { id: 'half-neck-rolls', name: 'Half Neck Rolls', pool: 'stretch', groups: ['shoulders'], equip: [], tier: 1, arch: 'neck-side', cue: 'Ear toward the shoulder, no shrugging', dose: 48 },
    { id: 'hands-clapped-forearms-stretch', name: 'Hands Clapped Forearms Stretch', pool: 'stretch', groups: ['shoulders'], equip: [], tier: 1, arch: 'cross-body-shoulder', cue: 'Straight arm across the chest, hug it in', dose: 48 },
    { id: 'lats-stretch-elbow-on-wall', name: 'Lats Stretch Elbow on Wall', pool: 'stretch', groups: ['shoulders'], equip: ['wall'], tier: 1, arch: 'arm-circles', cue: 'Reach long, shoulders loose', dose: 48 },
    { id: 'lats-stretch-on-wall', name: 'Lats Stretch on Wall', pool: 'stretch', groups: ['shoulders'], equip: ['wall'], tier: 1, arch: 'arm-circles', cue: 'Reach long, shoulders loose', dose: 48 },
    { id: 'one-arm-cow-face-pose-easy', name: 'One Arm Cow Face Pose - Easy', pool: 'stretch', groups: ['shoulders', 'spine'], equip: [], tier: 1, arch: 'cat-cow', cue: 'Round up on exhale, open on inhale', dose: 56 },
    { id: 'side-bend-standing-lats-stretch', name: 'Side Bend Standing Lats Stretch', pool: 'stretch', groups: ['shoulders', 'spine'], equip: [], tier: 1, arch: 'side-bend', cue: 'Reach over, feel the ribs open', dose: 48 },
    { id: 'side-chest-stretch-on-wall', name: 'Side Chest Stretch on Wall', pool: 'stretch', groups: ['shoulders'], equip: ['wall'], tier: 1, arch: 'arm-circles', cue: 'Reach long, shoulders loose', dose: 48 },
    { id: 'single-arm-extended-pull-downwards-biceps-st', name: 'Single Arm Extended Pull Downwards Biceps Stretch', pool: 'stretch', groups: ['shoulders'], equip: [], tier: 1, arch: 'cross-body-shoulder', cue: 'Straight arm across the chest, hug it in', dose: 48 },
    { id: 'single-arm-palm-down-on-wall-biceps-stretch', name: 'Single Arm Palm Down on Wall Biceps Stretch', pool: 'stretch', groups: ['shoulders'], equip: ['wall'], tier: 1, arch: 'cross-body-shoulder', cue: 'Straight arm across the chest, hug it in', dose: 48 },
    { id: 'single-arm-on-wall-side-biceps-stretch', name: 'Single Arm on Wall Side Biceps Stretch', pool: 'stretch', groups: ['shoulders'], equip: ['wall'], tier: 1, arch: 'cross-body-shoulder', cue: 'Straight arm across the chest, hug it in', dose: 48 },
    { id: 'bow-pose', name: 'Bow Pose', pool: 'stretch', groups: ['spine'], equip: [], tier: 1, arch: 'torso-twist', cue: 'Hips stay square, let arms follow', dose: 56 },
    { id: 'cat-pose', name: 'Cat Pose', pool: 'stretch', groups: ['spine'], equip: [], tier: 1, arch: 'cat-cow', cue: 'Round up on exhale, open on inhale', dose: 56 },
    { id: 'chair-pose', name: 'Chair Pose', pool: 'stretch', groups: ['spine'], equip: ['chair'], tier: 1, arch: 'torso-twist', cue: 'Hips stay square, let arms follow', dose: 56 },
    { id: 'child-pose-lower-back-stretch', name: 'Child Pose Lower Back Stretch', pool: 'stretch', groups: ['spine'], equip: [], tier: 1, arch: 'seated-fold', cue: 'Long spine first, then fold', dose: 56 },
    { id: 'cobra-stretch', name: 'Cobra Stretch', pool: 'stretch', groups: ['spine'], equip: [], tier: 1, arch: 'cobra-hold', cue: 'Press the chest open, shoulders away from the ears', dose: 48 },
    { id: 'crescent-moon-pose', name: 'Crescent Moon Pose', pool: 'stretch', groups: ['spine'], equip: [], tier: 1, arch: 'lunge-reach', cue: 'Sink the hips, reach tall', dose: 56 },
    { id: 'criss-cross-bow-tie-pose', name: 'Criss Cross Bow Tie Pose', pool: 'stretch', groups: ['spine'], equip: [], tier: 1, arch: 'torso-twist', cue: 'Hips stay square, let arms follow', dose: 56 },
    { id: 'crow-pose', name: 'Crow Pose', pool: 'stretch', groups: ['spine'], equip: [], tier: 1, arch: 'torso-twist', cue: 'Hips stay square, let arms follow', dose: 56 },
    { id: 'easy-seated-twist-pose', name: 'Easy Seated Twist Pose', pool: 'stretch', groups: ['spine'], equip: [], tier: 1, arch: 'torso-twist', cue: 'Hips stay square, let arms follow', dose: 56 },
    { id: 'extended-side-pose', name: 'Extended Side Pose', pool: 'stretch', groups: ['spine'], equip: [], tier: 1, arch: 'torso-twist', cue: 'Hips stay square, let arms follow', dose: 56 },
    { id: 'gate-pose-rounding-spine-looking-up', name: 'Gate Pose Rounding Spine Looking Up', pool: 'stretch', groups: ['spine'], equip: [], tier: 1, arch: 'torso-twist', cue: 'Hips stay square, let arms follow', dose: 56 },
    { id: 'half-lotus', name: 'Half Lotus', pool: 'stretch', groups: ['spine'], equip: [], tier: 1, arch: 'torso-twist', cue: 'Hips stay square, let arms follow', dose: 48 },
    { id: 'lord-of-the-dance', name: 'Lord of the Dance', pool: 'stretch', groups: ['spine'], equip: [], tier: 1, arch: 'torso-twist', cue: 'Hips stay square, let arms follow', dose: 48 },
    { id: 'lying-knee-hugs-lower-back-stretch', name: 'Lying Knee Hugs Lower Back Stretch', pool: 'stretch', groups: ['spine'], equip: [], tier: 1, arch: 'knee-hugs', cue: 'Hug the knee in, stand tall', dose: 56 },
    { id: 'puppy-pose', name: 'Puppy Pose', pool: 'stretch', groups: ['spine'], equip: [], tier: 1, arch: 'torso-twist', cue: 'Hips stay square, let arms follow', dose: 56 },
    { id: 'restful-cow-face-pose-legs', name: 'Restful Cow Face Pose Legs', pool: 'stretch', groups: ['spine'], equip: [], tier: 1, arch: 'cat-cow', cue: 'Round up on exhale, open on inhale', dose: 56 },
    { id: 'reverse-prayer', name: 'Reverse Prayer', pool: 'stretch', groups: ['spine'], equip: [], tier: 1, arch: 'torso-twist', cue: 'Hips stay square, let arms follow', dose: 48 },
    { id: 'scorpion-twist-pose', name: 'Scorpion Twist Pose', pool: 'stretch', groups: ['spine'], equip: [], tier: 1, arch: 'torso-twist', cue: 'Hips stay square, let arms follow', dose: 56 },
    { id: 'side-lying-parsva-savasana', name: 'Side Lying Parsva Savasana', pool: 'stretch', groups: ['spine'], equip: [], tier: 1, arch: 'supine-twist', cue: 'Knees drop one way, shoulders stay down', dose: 56 },
    { id: 'wild-thing-pose', name: 'Wild Thing Pose', pool: 'stretch', groups: ['spine'], equip: [], tier: 1, arch: 'torso-twist', cue: 'Hips stay square, let arms follow', dose: 56 },
    { id: 'alternate-hammer-curl-seated-dumbbells', name: 'Alternate Hammer Curl Seated Dumbbells', pool: 'strength', groups: ['arms'], equip: ['dumbbell'], tier: 2, arch: 'db-curl', cue: 'Keep your wrists straight to avoid putting unnecessary strain on them during' },
    { id: 'band-bent-over-one-arm-kickback', name: 'Band Bent Over One Arm Kickback', pool: 'strength', groups: ['arms'], equip: ['band'], tier: 3, arch: 'db-overhead-tri', cue: 'Ensure the resistance band is securely placed under your feet to avoid' },
    { id: 'band-close-grip-row', name: 'Band Close Grip Row', pool: 'strength', groups: ['arms', 'shoulders'], equip: ['band'], tier: 2, arch: 'db-row', cue: 'Ensure the resistance band is securely anchored to avoid slipping' },
    { id: 'band-close-grip-biceps-curl', name: 'Band Close-grip Biceps Curl', pool: 'strength', groups: ['arms'], equip: ['band'], tier: 2, arch: 'db-curl', cue: 'Ensure the resistance band is securely placed under your feet to avoid' },
    { id: 'band-concentration-curl', name: 'Band Concentration Curl', pool: 'strength', groups: ['arms'], equip: ['band'], tier: 2, arch: 'db-curl', cue: 'Ensure the resistance band is securely placed under your foot to avoid' },
    { id: 'band-cross-chest-biceps-curl', name: 'Band Cross Chest Biceps Curl', pool: 'strength', groups: ['arms'], equip: ['band'], tier: 2, arch: 'db-curl', cue: 'Ensure the resistance band is securely anchored to avoid slipping' },
    { id: 'band-incline-alternate-hammer-curl', name: 'Band Incline Alternate Hammer Curl', pool: 'strength', groups: ['arms'], equip: ['band'], tier: 2, arch: 'db-curl', cue: 'Ensure the resistance band is securely placed under the bench to avoid' },
    { id: 'band-incline-biceps-curl', name: 'Band Incline Biceps Curl', pool: 'strength', groups: ['arms'], equip: ['band'], tier: 2, arch: 'db-curl', cue: 'Ensure the resistance band is securely anchored under the bench to avoid' },
    { id: 'band-wrist-curl', name: 'Band Wrist Curl', pool: 'strength', groups: ['arms'], equip: ['band'], tier: 2, arch: 'wrist-circles', cue: 'Keep your forearm stationary on your thighs to isolate the wrist movement' },
    { id: 'barbell-curl', name: 'Barbell Curl', pool: 'strength', groups: ['arms'], equip: ['barbell'], tier: 2, arch: 'db-curl', cue: 'Keep your elbows stationary and close to your body throughout the movement' },
    { id: 'chair-triceps-dips', name: 'Chair Triceps Dips', pool: 'strength', groups: ['arms'], equip: ['chair'], tier: 2, arch: 'chair-dip', cue: 'Keep your back close to the chair to maintain proper form and avoid straining' },
    { id: 'close-grip-push-up', name: 'Close Grip Push Up', pool: 'strength', groups: ['arms', 'push'], equip: [], tier: 1, arch: 'diamond-pushup', cue: 'Focus on using your triceps and chest muscles to lift your body, keeping your' },
    { id: 'decline-chair-push-up-diamond', name: 'Decline Chair Push Up Diamond', pool: 'strength', groups: ['arms'], equip: ['chair'], tier: 1, arch: 'diamond-pushup', cue: 'Keep your core engaged throughout the exercise to maintain a straight body' },
    { id: 'diamond-push-up', name: 'Diamond Push Up', pool: 'strength', groups: ['arms'], equip: [], tier: 1, arch: 'diamond-pushup', cue: 'Ensure your elbows do not flare out; they should stay close to your body to' },
    { id: 'dip-on-floor-with-chair', name: 'Dip on Floor with Chair', pool: 'strength', groups: ['arms'], equip: ['chair'], tier: 2, arch: 'chair-dip', cue: 'Ensure your hands are firmly placed on the chair and your fingers are' },
    { id: 'floor-tricep-dip', name: 'Floor Tricep Dip', pool: 'strength', groups: ['arms'], equip: [], tier: 2, arch: 'chair-dip', cue: 'Elbows back, chest tall' },
    { id: 'alternate-single-leg-raise-plank', name: 'Alternate Single Leg Raise Plank', pool: 'strength', groups: ['carry', 'legs'], equip: [], tier: 1, arch: 'plank', cue: 'Keep your core engaged throughout the exercise to maintain stability and' },
    { id: 'alternating-plank-lunge', name: 'Alternating Plank Lunge', pool: 'strength', groups: ['carry', 'core'], equip: [], tier: 2, arch: 'reverse-lunge', cue: 'Step back, drop the knee, drive up' },
    { id: 'around-the-world-superman-hold', name: 'Around the World Superman Hold', pool: 'strength', groups: ['carry', 'pull'], equip: [], tier: 1, arch: 'prone-y-raise', cue: 'Engage your core and glutes to maintain stability and support your lower back' },
    { id: 'copenhagen-plank', name: 'Copenhagen Plank', pool: 'strength', groups: ['carry', 'core'], equip: ['bench'], tier: 3, arch: 'plank', cue: 'Squeeze glutes, ribs down, breathe' },
    { id: 'dumbbell-elbow-side-plank', name: 'Dumbbell Elbow Side Plank', pool: 'strength', groups: ['carry', 'core'], equip: ['dumbbell'], tier: 2, arch: 'side-plank', cue: 'Stack the hips, push the floor away' },
    { id: 'dumbbell-hand-side-plank', name: 'Dumbbell Hand Side Plank', pool: 'strength', groups: ['carry', 'core'], equip: ['dumbbell'], tier: 2, arch: 'side-plank', cue: 'Stack the hips, push the floor away' },
    { id: 'dumbbell-plank-pullthrough', name: 'Dumbbell Plank Pullthrough', pool: 'strength', groups: ['carry', 'shoulders'], equip: ['dumbbell'], tier: 2, arch: 'plank', cue: 'Squeeze glutes, ribs down, breathe' },
    { id: 'dumbbell-side-plank-up-down', name: 'Dumbbell Side Plank Up Down', pool: 'strength', groups: ['carry', 'core'], equip: ['dumbbell'], tier: 2, arch: 'side-plank', cue: 'Stack the hips, push the floor away' },
    { id: 'hand-stand-hold', name: 'Hand Stand Hold', pool: 'strength', groups: ['carry', 'core'], equip: [], tier: 3, arch: 'db-carry', cue: 'Tall and tight, grip hard, walk if you can' },
    { id: 'long-lever-plank', name: 'Long Lever Plank', pool: 'strength', groups: ['carry', 'core'], equip: [], tier: 3, arch: 'plank', cue: 'Squeeze glutes, ribs down, breathe' },
    { id: 'resistance-band-side-plank-glute-raise', name: 'Resistance Band Side Plank Glute Raise', pool: 'strength', groups: ['carry', 'legs'], equip: ['band'], tier: 2, arch: 'side-plank', cue: 'Focus on engaging your glutes and hip abductors throughout the movement' },
    { id: 'reverse-plank', name: 'Reverse Plank', pool: 'strength', groups: ['carry', 'core'], equip: [], tier: 1, arch: 'plank', cue: 'Squeeze glutes, ribs down, breathe' },
    { id: 'unilateral-front-plank', name: 'Unilateral Front Plank', pool: 'strength', groups: ['carry', 'core'], equip: [], tier: 1, arch: 'plank', cue: 'Squeeze glutes, ribs down, breathe' },
    { id: 'unilateral-plank', name: 'Unilateral Plank', pool: 'strength', groups: ['carry', 'core'], equip: [], tier: 1, arch: 'plank', cue: 'Squeeze glutes, ribs down, breathe' },
    { id: 'wall-sit-bodyweight', name: 'Wall Sit Bodyweight', pool: 'strength', groups: ['carry', 'legs'], equip: ['wall'], tier: 1, arch: 'wall-sit', cue: 'Ensure your knees do not extend past your toes to avoid placing unnecessary' },
    { id: '3-4-sit-up', name: '3-4 Sit-up', pool: 'strength', groups: ['core'], equip: [], tier: 1, arch: 'crunch-reach', cue: 'Keep your core engaged throughout the exercise to avoid straining your lower' },
    { id: '90-degree-heels-touch', name: '90 Degree Heels Touch', pool: 'strength', groups: ['core'], equip: [], tier: 1, arch: 'butt-kicks', cue: 'Keep your neck relaxed and avoid straining it by using your core muscles to' },
    { id: 'ab-crunches', name: 'Ab Crunches', pool: 'strength', groups: ['core'], equip: [], tier: 1, arch: 'crunch-reach', cue: 'Curl the ribs toward the hips' },
    { id: 'ab-mat-sit-up', name: 'Ab Mat Sit-up', pool: 'strength', groups: ['core'], equip: [], tier: 1, arch: 'crunch-reach', cue: 'Engage your core muscles throughout the movement to maximize effectiveness' },
    { id: 'abs-snails', name: 'Abs Snails', pool: 'strength', groups: ['core'], equip: [], tier: 1, arch: 'crunch-reach', cue: 'Curl the ribs toward the hips' },
    { id: 'air-twisting-crunch', name: 'Air Twisting Crunch', pool: 'strength', groups: ['core'], equip: [], tier: 1, arch: 'crunch-reach', cue: 'Keep your core engaged throughout the exercise to maximize muscle activation' },
    { id: 'alternate-leg-pull', name: 'Alternate Leg Pull', pool: 'strength', groups: ['core'], equip: [], tier: 1, arch: 'crunch-reach', cue: 'Keep your core engaged throughout the exercise to maximize muscle activation' },
    { id: 'alternate-leg-raise', name: 'Alternate Leg Raise', pool: 'strength', groups: ['core'], equip: [], tier: 1, arch: 'hang-knee-raise', cue: 'Keep your core engaged throughout the exercise to maintain stability and' },
    { id: 'alternate-lying-floor-leg-raise', name: 'Alternate Lying Floor Leg Raise', pool: 'strength', groups: ['core'], equip: [], tier: 1, arch: 'hang-knee-raise', cue: 'Focus on keeping your upper back pressed into the mat to avoid arching and' },
    { id: 'alternate-oblique-crunch', name: 'Alternate Oblique Crunch', pool: 'strength', groups: ['core'], equip: [], tier: 1, arch: 'crunch-reach', cue: 'Focus on using your oblique muscles to twist your torso rather than pulling' },
    { id: 'alternating-oblique-sit-ups', name: 'Alternating Oblique Sit-ups', pool: 'strength', groups: ['core'], equip: [], tier: 1, arch: 'crunch-reach', cue: 'Curl the ribs toward the hips' },
    { id: 'band-bicycle-crunch', name: 'Band Bicycle Crunch', pool: 'strength', groups: ['core'], equip: ['band'], tier: 2, arch: 'crunch-reach', cue: 'Avoid pulling on your neck with your hands; use your abs to lift and twist' },
    { id: 'band-decline-sit-up', name: 'Band Decline Sit Up', pool: 'strength', groups: ['core'], equip: ['band'], tier: 2, arch: 'crunch-reach', cue: 'Ensure the resistance band is securely anchored behind the headrest to avoid' },
    { id: 'band-side-bend', name: 'Band Side Bend', pool: 'strength', groups: ['core'], equip: ['band'], tier: 2, arch: 'side-bend', cue: 'Engage your core to help stabilize your body and prevent unnecessary movement' },
    { id: 'bent-knee-lying-twist', name: 'Bent Knee Lying Twist', pool: 'strength', groups: ['core'], equip: [], tier: 1, arch: 'supine-twist', cue: 'Keep your shoulders flat on the floor to maximize the stretch in your spine' },
    { id: 'brazilian-crunches', name: 'Brazilian Crunches', pool: 'strength', groups: ['core'], equip: [], tier: 1, arch: 'crunch-reach', cue: 'Keep your movements controlled to ensure each repetition is deliberate and' },
    { id: 'dragonfly', name: 'Dragonfly', pool: 'strength', groups: ['core'], equip: [], tier: 3, arch: 'crunch-reach', cue: 'Curl the ribs toward the hips' },
    { id: 'hanging-leg-raises', name: 'Hanging Leg Raises', pool: 'strength', groups: ['core'], equip: ['bar'], tier: 2, arch: 'hang-knee-raise', cue: 'No swinging — curl the hips up' },
    { id: 'resistance-band-lying-bent-knee-raise', name: 'Resistance Band Lying Bent Knee Raise', pool: 'strength', groups: ['core'], equip: ['band'], tier: 2, arch: 'hang-knee-raise', cue: 'Focus on engaging your abdominals throughout the movement' },
    { id: 'alternating-hamstring-curl', name: 'Alternating Hamstring Curl', pool: 'strength', groups: ['hinge'], equip: [], tier: 1, arch: 'db-curl', cue: 'Perform the movement slowly and with control to maximize muscle activation' },
    { id: 'band-deadlift', name: 'Band Deadlift', pool: 'strength', groups: ['hinge'], equip: ['band'], tier: 2, arch: 'bb-deadlift', cue: 'Ensure the resistance band is securely placed under your feet to avoid' },
    { id: 'banded-feet-elevated-hip-thrusters', name: 'Banded Feet Elevated Hip Thrusters', pool: 'strength', groups: ['hinge'], equip: ['band'], tier: 2, arch: 'db-thruster', cue: 'Ensure the resistance band stays under consistent tension throughout the' },
    { id: 'barbell-clean-deadlift', name: 'Barbell Clean Deadlift', pool: 'strength', groups: ['hinge'], equip: ['barbell'], tier: 3, arch: 'bb-deadlift', cue: 'Maintain a neutral spine to avoid rounding your back and prevent injury' },
    { id: 'barbell-deadlift', name: 'Barbell Deadlift', pool: 'strength', groups: ['hinge'], equip: ['barbell'], tier: 2, arch: 'bb-deadlift', cue: 'Keep your head in line with your spine to maintain proper neck alignment and' },
    { id: 'barbell-feet-elevated-glute-bridge', name: 'Barbell Feet Elevated Glute Bridge', pool: 'strength', groups: ['hinge'], equip: ['barbell'], tier: 2, arch: 'glute-bridge', cue: 'Exhale as you lift your hips and inhale as you lower them' },
    { id: 'barbell-glute-bridge-hands-on-bar', name: 'Barbell Glute Bridge (hands on Bar)', pool: 'strength', groups: ['hinge'], equip: ['barbell'], tier: 2, arch: 'glute-bridge', cue: 'Drive through your heels to engage your glutes and hamstrings effectively' },
    { id: 'barbell-kas-glute-bridge', name: 'Barbell Kas Glute Bridge', pool: 'strength', groups: ['hinge'], equip: ['barbell'], tier: 2, arch: 'glute-bridge', cue: 'Drive through your heels to engage your glutes and hamstrings effectively' },
    { id: 'bodyweight-feet-elevated-figure-four-glute-b', name: 'Bodyweight Feet Elevated Figure Four Glute Bridge', pool: 'strength', groups: ['hinge'], equip: [], tier: 1, arch: 'glute-bridge', cue: 'Drive through the heels, squeeze hard' },
    { id: 'bodyweight-feet-elevated-staggered-glute-bri', name: 'Bodyweight Feet Elevated Staggered Glute Bridge', pool: 'strength', groups: ['hinge'], equip: [], tier: 1, arch: 'glute-bridge', cue: 'Drive through the heels, squeeze hard' },
    { id: 'bodyweight-hip-thrust', name: 'Bodyweight Hip Thrust', pool: 'strength', groups: ['hinge'], equip: [], tier: 1, arch: 'glute-bridge', cue: 'Drive through the heels, squeeze hard' },
    { id: 'dumbbell-feet-elevated-glute-bridge', name: 'Dumbbell Feet Elevated Glute Bridge', pool: 'strength', groups: ['hinge'], equip: ['dumbbell'], tier: 2, arch: 'glute-bridge', cue: 'Ensure your feet are firm and secure on the elevated surface throughout the' },
    { id: 'glute-bridge-bodyweight', name: 'Glute Bridge Bodyweight', pool: 'strength', groups: ['hinge'], equip: [], tier: 1, arch: 'glute-bridge', cue: 'Drive through the heels, squeeze hard' },
    { id: 'glute-bridge-with-abduction-bodyweight', name: 'Glute Bridge with Abduction Bodyweight', pool: 'strength', groups: ['hinge'], equip: [], tier: 1, arch: 'glute-bridge', cue: 'Drive through the heels, squeeze hard' },
    { id: 'good-mornings', name: 'Good Mornings', pool: 'strength', groups: ['hinge'], equip: [], tier: 1, arch: 'good-morning', cue: 'Push the hips back, flat back' },
    { id: '4-reverse-lunge-and-4-side-taps', name: '4 Reverse Lunge and 4 Side Taps', pool: 'strength', groups: ['legs'], equip: [], tier: 2, arch: 'reverse-lunge', cue: 'Keep your core muscles engaged to maintain balance and stability during' },
    { id: 'alternating-step-out', name: 'Alternating Step Out', pool: 'strength', groups: ['legs'], equip: [], tier: 1, arch: 'squat', cue: 'Focus on keeping your upper body upright and avoid leaning too far forward or' },
    { id: 'ankle-pumps', name: 'Ankle Pumps', pool: 'strength', groups: ['legs'], equip: [], tier: 1, arch: 'squat', cue: 'Chest up, sit back, knees track out' },
    { id: 'band-single-leg-split-squat', name: 'Band Single Leg Split Squat', pool: 'strength', groups: ['legs'], equip: ['band'], tier: 2, arch: 'split-squat', cue: 'Maintain an upright torso throughout the exercise to avoid leaning forward' },
    { id: 'band-spanish-split-squat', name: 'Band Spanish Split Squat', pool: 'strength', groups: ['legs'], equip: ['band'], tier: 2, arch: 'split-squat', cue: 'Keep your torso upright and avoid leaning forward during the movement' },
    { id: 'band-standing-leg-curl', name: 'Band Standing Leg Curl', pool: 'strength', groups: ['legs'], equip: ['band'], tier: 2, arch: 'db-curl', cue: 'Focus on squeezing your hamstrings at the top of the movement to enhance' },
    { id: 'barbell-bench-squat', name: 'Barbell Bench Squat', pool: 'strength', groups: ['legs'], equip: ['barbell', 'bench'], tier: 2, arch: 'bb-squat', cue: 'Ensure your knees track over your toes to prevent knee injuries and ensure' },
    { id: 'barbell-box-squat', name: 'Barbell Box Squat', pool: 'strength', groups: ['legs'], equip: ['barbell', 'bench'], tier: 2, arch: 'bb-squat', cue: 'Ensure your knees track over your toes to prevent knee injuries and ensure' },
    { id: 'barbell-curtsy-lunge', name: 'Barbell Curtsy Lunge', pool: 'strength', groups: ['legs'], equip: ['barbell'], tier: 2, arch: 'reverse-lunge', cue: 'Ensure your front knee tracks over your toes to prevent knee injuries and' },
    { id: 'barbell-front-squat', name: 'Barbell Front Squat', pool: 'strength', groups: ['legs'], equip: ['barbell'], tier: 2, arch: 'bb-squat', cue: 'Exhale as you stand up from the squat and inhale as you lower into the squat' },
    { id: 'barbell-full-squat', name: 'Barbell Full Squat', pool: 'strength', groups: ['legs'], equip: ['barbell'], tier: 2, arch: 'bb-squat', cue: 'Keep your chest up and back straight to maintain proper posture and alignment' },
    { id: 'barbell-jump-squat', name: 'Barbell Jump Squat', pool: 'strength', groups: ['legs'], equip: ['barbell'], tier: 2, arch: 'bb-squat', cue: 'Ensure the barbell remains steady on your back to prevent it from shifting' },
    { id: 'barbell-lateral-lunge', name: 'Barbell Lateral Lunge', pool: 'strength', groups: ['legs'], equip: ['barbell'], tier: 2, arch: 'reverse-lunge', cue: 'Focus on a controlled descent to maximize muscle engagement and prevent injury' },
    { id: 'barbell-low-bar-squat', name: 'Barbell Low Bar Squat', pool: 'strength', groups: ['legs'], equip: ['barbell'], tier: 2, arch: 'bb-squat', cue: 'Distribute your weight evenly across your feet to maintain balance and' },
    { id: 'barbell-lunge', name: 'Barbell Lunge', pool: 'strength', groups: ['legs'], equip: ['barbell'], tier: 2, arch: 'reverse-lunge', cue: 'Use a weight that allows for proper form and technique throughout the exercise' },
    { id: 'bodyweight-kneeling-sissy-squat', name: 'Bodyweight Kneeling Sissy Squat', pool: 'strength', groups: ['legs'], equip: [], tier: 2, arch: 'squat', cue: 'Chest up, sit back, knees track out' },
    { id: 'bodyweight-rear-lunge', name: 'Bodyweight Rear Lunge', pool: 'strength', groups: ['legs'], equip: [], tier: 2, arch: 'reverse-lunge', cue: 'Maintain an upright posture throughout the exercise to ensure proper form' },
    { id: 'bodyweight-squat', name: 'Bodyweight Squat', pool: 'strength', groups: ['legs'], equip: [], tier: 2, arch: 'squat', cue: 'Keep your feet flat on the floor to maintain balance and stability' },
    { id: 'bodyweight-wall-squat', name: 'Bodyweight Wall Squat', pool: 'strength', groups: ['legs'], equip: ['wall'], tier: 2, arch: 'squat', cue: 'Start the movement by engaging your glutes and core to maintain stability' },
    { id: 'bulgarian-split-squat', name: 'Bulgarian Split Squat', pool: 'strength', groups: ['legs'], equip: [], tier: 2, arch: 'split-squat', cue: 'Keep your front knee aligned with your toes to avoid putting unnecessary' },
    { id: 'burpee-squat', name: 'Burpee Squat', pool: 'strength', groups: ['legs'], equip: [], tier: 3, arch: 'squat', cue: 'Start with a moderate pace to master the form, then gradually increase your' },
    { id: 'calf-raise-clap', name: 'Calf Raise Clap', pool: 'strength', groups: ['legs'], equip: [], tier: 3, arch: 'calf-raise', cue: 'Keep your head up and eyes forward to maintain proper alignment and balance' },
    { id: 'clamshell', name: 'Clamshell', pool: 'strength', groups: ['legs'], equip: [], tier: 1, arch: 'squat', cue: 'Chest up, sit back, knees track out' },
    { id: 'dumbbell-frog-jumps', name: 'Dumbbell Frog Jumps', pool: 'strength', groups: ['legs'], equip: ['dumbbell'], tier: 2, arch: 'frog-rocks', cue: 'Use explosive power from your legs to jump up' },
    { id: 'frog-jumps', name: 'Frog Jumps', pool: 'strength', groups: ['legs'], equip: [], tier: 2, arch: 'frog-rocks', cue: 'Rock back into the hips, easy breath' },
    { id: 'in-and-out-squats', name: 'In and Out Squats', pool: 'strength', groups: ['legs'], equip: [], tier: 1, arch: 'squat', cue: 'Land softly on your forefeet to reduce impact on your joints' },
    { id: 'jumping-lunge', name: 'Jumping Lunge', pool: 'strength', groups: ['legs'], equip: [], tier: 2, arch: 'reverse-lunge', cue: 'Step back, drop the knee, drive up' },
    { id: 'jumping-pistol-squat', name: 'Jumping Pistol Squat', pool: 'strength', groups: ['legs'], equip: [], tier: 3, arch: 'squat', cue: 'Chest up, sit back, knees track out' },
    { id: 'resistance-band-squat', name: 'Resistance Band Squat', pool: 'strength', groups: ['legs'], equip: ['band'], tier: 2, arch: 'squat', cue: 'Keep your chest up and lean slightly forward to maintain proper form' },
    { id: 'sissy-squat-bodyweight', name: 'Sissy Squat Bodyweight', pool: 'strength', groups: ['legs'], equip: [], tier: 2, arch: 'squat', cue: 'Chest up, sit back, knees track out' },
    { id: 'wall-squat-bodyweight', name: 'Wall Squat Bodyweight', pool: 'strength', groups: ['legs'], equip: ['wall'], tier: 2, arch: 'squat', cue: 'Ensure your knees do not extend past your toes to avoid placing unnecessary' },
    { id: 'alternating-superman', name: 'Alternating Superman', pool: 'strength', groups: ['pull'], equip: [], tier: 1, arch: 'prone-y-raise', cue: 'Engage your core throughout the exercise to maintain stability and protect' },
    { id: 'band-bent-over-row', name: 'Band Bent-over Row', pool: 'strength', groups: ['pull'], equip: ['band'], tier: 2, arch: 'db-row', cue: 'Ensure the resistance band is securely placed under your feet to avoid' },
    { id: 'band-fixed-back-underhand-pulldown', name: 'Band Fixed Back Underhand Pulldown', pool: 'strength', groups: ['pull'], equip: ['band'], tier: 2, arch: 'band-pull-apart', cue: 'Ensure the resistance band is securely anchored to avoid slipping' },
    { id: 'band-lying-reverse-grip-row', name: 'Band Lying Reverse Grip Row', pool: 'strength', groups: ['pull'], equip: ['band'], tier: 2, arch: 'db-row', cue: 'Maintain a neutral spine throughout the exercise to avoid straining your' },
    { id: 'band-pull-up', name: 'Band Pull Up', pool: 'strength', groups: ['pull'], equip: ['band', 'bar'], tier: 2, arch: 'pull-up', cue: 'Chest to the bar, control the way down' },
    { id: 'barbell-bent-over-row', name: 'Barbell Bent Over Row', pool: 'strength', groups: ['pull'], equip: ['barbell'], tier: 2, arch: 'db-row', cue: 'Avoid rounding your back by keeping your chest up and your spine neutral' },
    { id: 'barbell-clean-pull', name: 'Barbell Clean Pull', pool: 'strength', groups: ['pull'], equip: ['barbell'], tier: 3, arch: 'db-row', cue: 'Focus on leg drive to generate power from your lower body during the lift' },
    { id: 'barbell-deadlift-high-pull', name: 'Barbell Deadlift High Pull', pool: 'strength', groups: ['pull'], equip: ['barbell'], tier: 2, arch: 'bb-deadlift', cue: 'Use a weight that allows you to maintain proper form throughout the exercise' },
    { id: 'barbell-meadows-row', name: 'Barbell Meadows Row', pool: 'strength', groups: ['pull'], equip: ['barbell'], tier: 2, arch: 'db-row', cue: 'Squeeze your shoulder blade at the top of the movement to enhance muscle' },
    { id: 'lawnmower-row', name: 'Lawnmower Row', pool: 'strength', groups: ['pull'], equip: [], tier: 2, arch: 'db-row', cue: 'Pull to the ribs, no shrugging' },
    { id: 'push-pull-chair-over-head-pull', name: 'Push Pull Chair Over Head Pull', pool: 'strength', groups: ['pull'], equip: ['chair'], tier: 1, arch: 'db-row', cue: 'Pull to the ribs, no shrugging' },
    { id: 'push-up-to-renegade-row', name: 'Push-Up to Renegade Row', pool: 'strength', groups: ['pull'], equip: [], tier: 2, arch: 'db-renegade-row', cue: 'Wide feet, hips do not rotate' },
    { id: 'resistance-band-cross-body-single-straight-a', name: 'Resistance Band Cross Body Single Straight Arm Supinated Pulldown', pool: 'strength', groups: ['pull'], equip: ['band'], tier: 2, arch: 'arm-swings', cue: 'Exhale as you pull the band down and inhale as you release it back up' },
    { id: 'resistance-band-floor-hyperextension', name: 'Resistance Band Floor Hyperextension', pool: 'strength', groups: ['pull'], equip: ['band'], tier: 2, arch: 'good-morning', cue: 'Keep your neck in a neutral position to avoid straining it' },
    { id: 'resistance-band-kneeling-cross-body-single-s', name: 'Resistance Band Kneeling Cross Body Single Straight Arm Supinated Pulldown', pool: 'strength', groups: ['pull'], equip: ['band'], tier: 2, arch: 'arm-swings', cue: 'Exhale as you pull the band down and inhale as you release it back up' },
    { id: 'resistance-band-lying-hyperextension-abducti', name: 'Resistance Band Lying Hyperextension Abduction', pool: 'strength', groups: ['pull'], equip: ['band'], tier: 2, arch: 'good-morning', cue: 'Focus on engaging your glutes and hip abductors throughout the movement' },
    { id: 'theraband-scapula-retraction', name: 'Theraband Scapula Retraction', pool: 'strength', groups: ['pull'], equip: [], tier: 1, arch: 'db-row', cue: 'Pull to the ribs, no shrugging' },
    { id: 'archer-push-up', name: 'Archer Push Up', pool: 'strength', groups: ['push'], equip: [], tier: 3, arch: 'pushup', cue: 'Ensure your shoulders and hips stay level to avoid any imbalance during the' },
    { id: 'band-bench-press', name: 'Band Bench Press', pool: 'strength', groups: ['push', 'shoulders'], equip: ['band', 'bench'], tier: 2, arch: 'bb-bench', cue: 'Ensure the resistance band is securely placed under the bench to avoid' },
    { id: 'band-chest-fly', name: 'Band Chest Fly', pool: 'strength', groups: ['push'], equip: ['band'], tier: 2, arch: 'bb-bench', cue: 'Ensure the resistance band is securely anchored to avoid slipping' },
    { id: 'band-cross-body-one-arm-chest-press', name: 'Band Cross Body One Arm Chest Press', pool: 'strength', groups: ['push', 'shoulders'], equip: ['band'], tier: 3, arch: 'arm-swings', cue: 'Ensure the resistance band is securely anchored to avoid slipping' },
    { id: 'band-high-fly', name: 'Band High Fly', pool: 'strength', groups: ['push'], equip: ['band'], tier: 2, arch: 'bb-bench', cue: 'Ensure the resistance band is securely anchored to avoid slipping' },
    { id: 'band-incline-bench-press', name: 'Band Incline Bench Press', pool: 'strength', groups: ['push', 'shoulders'], equip: ['band', 'bench'], tier: 2, arch: 'bb-bench', cue: 'Ensure the resistance band is securely anchored under the bench to avoid' },
    { id: 'band-incline-fly', name: 'Band Incline Fly', pool: 'strength', groups: ['push'], equip: ['band'], tier: 2, arch: 'bb-bench', cue: 'Ensure the resistance band is securely anchored under the bench to avoid' },
    { id: 'band-low-chest-fly', name: 'Band Low Chest Fly', pool: 'strength', groups: ['push'], equip: ['band'], tier: 2, arch: 'bb-bench', cue: 'Keep a slight bend in your elbows to protect your shoulder joints' },
    { id: 'band-low-chest-press', name: 'Band Low Chest Press', pool: 'strength', groups: ['push', 'shoulders'], equip: ['band'], tier: 2, arch: 'bb-bench', cue: 'Exhale as you press the band handles forward and inhale as you return it back' },
    { id: 'band-palloff-press', name: 'Band Palloff Press', pool: 'strength', groups: ['push', 'shoulders'], equip: ['band'], tier: 2, arch: 'pushup', cue: 'Maintain an upright posture and avoid leaning towards or away from the anchor' },
    { id: 'barbell-bench-press', name: 'Barbell Bench Press', pool: 'strength', groups: ['push', 'shoulders'], equip: ['barbell', 'bench'], tier: 2, arch: 'bb-bench', cue: 'Keep your feet flat on the floor to maintain stability and support your lower' },
    { id: 'barbell-floor-chest-press', name: 'Barbell Floor Chest Press', pool: 'strength', groups: ['push', 'shoulders'], equip: ['barbell'], tier: 2, arch: 'bb-bench', cue: 'Lower the barbell slowly and with control to maximize muscle engagement and' },
    { id: 'barbell-incline-bench-press', name: 'Barbell Incline Bench Press', pool: 'strength', groups: ['push', 'shoulders'], equip: ['barbell', 'bench'], tier: 2, arch: 'bb-bench', cue: 'Breathe steadily, exhaling as you press the barbell up and inhaling as you' },
    { id: 'chest-tap-push-up', name: 'Chest Tap Push Up', pool: 'strength', groups: ['push'], equip: [], tier: 1, arch: 'pushup', cue: 'Perform the movement with control, especially when lowering your body, to' },
    { id: 'clap-push-ups', name: 'Clap Push Ups', pool: 'strength', groups: ['push'], equip: [], tier: 3, arch: 'pushup', cue: 'Focus on using your chest, shoulders, and triceps to generate the explosive' },
    { id: 'clock-push-ups', name: 'Clock Push Ups', pool: 'strength', groups: ['push'], equip: [], tier: 1, arch: 'pushup', cue: 'Focus on maintaining proper form during each push-up, ensuring your elbows' },
    { id: 'kneeling-push-up', name: 'Kneeling Push-up', pool: 'strength', groups: ['push'], equip: [], tier: 1, arch: 'pushup', cue: 'One straight line, elbows back not out' },
    { id: 'one-arm-push-up', name: 'One Arm Push Up', pool: 'strength', groups: ['push'], equip: [], tier: 3, arch: 'pushup', cue: 'One straight line, elbows back not out' },
    { id: 'arm-tuck-side-bend', name: 'Arm Tuck Side Bend', pool: 'strength', groups: ['shoulders'], equip: [], tier: 1, arch: 'side-bend', cue: 'Focus on keeping your shoulder relaxed to avoid tension in your neck and' },
    { id: 'arms-lateral-raise-and-rotation-up', name: 'Arms Lateral Raise and Rotation Up', pool: 'strength', groups: ['shoulders'], equip: [], tier: 1, arch: 'torso-twist', cue: 'Hips stay square, let arms follow' },
    { id: 'backhand-raise', name: 'Backhand Raise', pool: 'strength', groups: ['shoulders'], equip: [], tier: 1, arch: 'db-shoulder-press', cue: 'Engage your core to maintain stability and support your lower back throughout' },
    { id: 'band-face-pull', name: 'Band Face Pull', pool: 'strength', groups: ['shoulders'], equip: ['band'], tier: 2, arch: 'band-pull-apart', cue: 'Ensure the resistance band is securely anchored to avoid slipping' },
    { id: 'band-front-face-pull', name: 'Band Front Face Pull', pool: 'strength', groups: ['shoulders'], equip: ['band'], tier: 2, arch: 'band-pull-apart', cue: 'Ensure the resistance band is securely anchored to avoid slipping' },
    { id: 'band-front-raise', name: 'Band Front Raise', pool: 'strength', groups: ['shoulders'], equip: ['band'], tier: 2, arch: 'db-lateral-raise', cue: 'Ensure the resistance band is securely placed under your feet to avoid' },
    { id: 'elevated-pike-shoulder-shrug', name: 'Elevated Pike Shoulder Shrug', pool: 'strength', groups: ['shoulders'], equip: [], tier: 1, arch: 'shoulder-rolls', cue: 'Big circles back, chest opens' },
    { id: 'handstand-push-on-chair', name: 'Handstand Push on Chair', pool: 'strength', groups: ['shoulders'], equip: ['chair'], tier: 3, arch: 'pike-pushup', cue: 'Engage your core throughout the exercise to maintain stability and prevent' },
    { id: 'laying-lateral-raise', name: 'Laying Lateral Raise', pool: 'strength', groups: ['shoulders'], equip: [], tier: 1, arch: 'db-lateral-raise', cue: 'Lead with the elbows, stop at shoulder height' },
    { id: 'air-bike-crunch', name: 'Air Bike Crunch', pool: 'sweat', groups: ['core'], equip: [], tier: 1, arch: 'crunch-reach', cue: 'Keep your core engaged throughout the exercise to maximize muscle activation' },
    { id: 'bear-crawls', name: 'Bear Crawls', pool: 'sweat', groups: ['core', 'floor'], equip: [], tier: 1, arch: 'bear-crawl', cue: 'Knees hover, opposite hand and foot' },
    { id: 'bicycle-twisting-crunch', name: 'Bicycle Twisting Crunch', pool: 'sweat', groups: ['core'], equip: [], tier: 1, arch: 'crunch-reach', cue: 'Focus on using your abdominal muscles to perform the twist, rather than your' },
    { id: 'bicycles-crunches', name: 'Bicycles Crunches', pool: 'sweat', groups: ['core'], equip: [], tier: 1, arch: 'crunch-reach', cue: 'Focus on using your abdominal muscles to perform the twist, rather than your' },
    { id: 'bridge-mountain-climber-cross-body', name: 'Bridge - Mountain Climber (cross Body)', pool: 'sweat', groups: ['core', 'floor', 'upper'], equip: [], tier: 1, arch: 'arm-swings', cue: 'Ensure you keep your movements smooth and controlled to maintain form and' },
    { id: 'crab-twist-toe-touch', name: 'Crab Twist Toe Touch', pool: 'sweat', groups: ['core'], equip: [], tier: 1, arch: 'seated-fold', cue: 'Perform the twist with control to maximize muscle activation and prevent' },
    { id: 'criss-cross-leg-raises', name: 'Criss Cross Leg Raises', pool: 'sweat', groups: ['core', 'upper'], equip: [], tier: 1, arch: 'hang-knee-raise', cue: 'Keep your core engaged throughout the exercise to maintain stability and' },
    { id: 'double-knee-drive', name: 'Double Knee Drive', pool: 'sweat', groups: ['core'], equip: [], tier: 1, arch: 'knee-strikes', cue: 'Keep your upper body upright and avoid leaning too far forward or backward to' },
    { id: 'flat-knee-raise', name: 'Flat Knee Raise', pool: 'sweat', groups: ['core', 'upper'], equip: [], tier: 1, arch: 'hang-knee-raise', cue: 'No swinging — curl the hips up' },
    { id: 'mountain-climber-jumps', name: 'Mountain Climber Jumps', pool: 'sweat', groups: ['core', 'floor', 'impact'], equip: [], tier: 2, arch: 'mountain-climbers', cue: 'Hips low, drive the knees in fast' },
    { id: 'mountain-climbers', name: 'Mountain Climbers', pool: 'sweat', groups: ['core', 'floor'], equip: [], tier: 1, arch: 'mountain-climbers', cue: 'Ensure you keep your movements smooth and controlled to maintain form and' },
    { id: 'plank-individual-arm-reach', name: 'Plank Individual Arm Reach', pool: 'sweat', groups: ['core', 'floor', 'upper'], equip: [], tier: 1, arch: 'plank', cue: 'Squeeze glutes, ribs down, breathe' },
    { id: 'plank-jack', name: 'Plank Jack', pool: 'sweat', groups: ['core', 'floor', 'impact'], equip: [], tier: 1, arch: 'plank', cue: 'Move quickly but with control to maximize muscle engagement and prevent injury' },
    { id: 'plank-knee-tucks', name: 'Plank Knee Tucks', pool: 'sweat', groups: ['core', 'floor'], equip: [], tier: 1, arch: 'plank', cue: 'Use controlled, explosive movements to quickly bring your knees to your chest' },
    { id: 'plank-push-up', name: 'Plank Push-Up', pool: 'sweat', groups: ['core', 'floor', 'upper'], equip: [], tier: 1, arch: 'plank', cue: 'Squeeze glutes, ribs down, breathe' },
    { id: 'plank-reach-through', name: 'Plank Reach Through', pool: 'sweat', groups: ['core', 'floor'], equip: [], tier: 1, arch: 'plank', cue: 'Engage your core throughout the exercise to maintain stability and support' },
    { id: 'plank-shoulder-taps', name: 'Plank Shoulder Taps', pool: 'sweat', groups: ['core', 'floor', 'upper'], equip: [], tier: 1, arch: 'plank', cue: 'Keep your hips level throughout the movement to maintain proper form and' },
    { id: 'scissors-kick', name: 'Scissors Kick', pool: 'sweat', groups: ['core', 'impact', 'low'], equip: [], tier: 1, arch: 'split-jump', cue: 'Ensure your lower back remains pressed against the floor to avoid strain and' },
    { id: 'spider-plank', name: 'Spider Plank', pool: 'sweat', groups: ['core', 'floor'], equip: [], tier: 1, arch: 'plank', cue: 'Breathe steadily throughout the exercise, exhaling as you bring your knee' },
    { id: 'standing-toe-touch', name: 'Standing Toe Touch', pool: 'sweat', groups: ['core'], equip: [], tier: 1, arch: 'seated-fold', cue: 'Focus on keeping both your leg and arm straight throughout the movement' },
    { id: 'burpee', name: 'Burpee', pool: 'sweat', groups: ['floor', 'impact'], equip: [], tier: 3, arch: 'burpee', cue: 'Start with a moderate pace to master the form, then gradually increase your' },
    { id: 'dumbbell-burpee', name: 'Dumbbell Burpee', pool: 'sweat', groups: ['floor', 'impact'], equip: ['dumbbell'], tier: 3, arch: 'burpee', cue: 'Land softly on your feet to minimize impact on your joints' },
    { id: 'half-burpees', name: 'Half Burpees', pool: 'sweat', groups: ['floor', 'impact'], equip: [], tier: 3, arch: 'burpee', cue: 'Focus on steady breathing, exhaling as you jump your feet forward and back' },
    { id: 'butt-kick-with-row', name: 'Butt Kick with Row', pool: 'sweat', groups: ['impact', 'low'], equip: [], tier: 1, arch: 'db-row', cue: 'Keep your upper body upright to maintain proper form and avoid leaning forward' },
    { id: 'butt-kicks', name: 'Butt Kicks', pool: 'sweat', groups: ['impact'], equip: [], tier: 1, arch: 'butt-kicks', cue: 'Keep your upper body upright and avoid leaning forward to maintain proper form' },
    { id: 'clap-jack', name: 'Clap Jack', pool: 'sweat', groups: ['impact'], equip: [], tier: 3, arch: 'jumping-jacks', cue: 'Ensure your knees are slightly bent during the jumps to absorb impact and' },
    { id: 'criss-cross-jack', name: 'Criss Cross Jack', pool: 'sweat', groups: ['impact', 'upper'], equip: [], tier: 1, arch: 'cross-jacks', cue: 'Focus on using your leg, chest and shoulder muscles to perform the jumps and' },
    { id: 'criss-cross-jump', name: 'Criss Cross Jump', pool: 'sweat', groups: ['impact', 'upper'], equip: [], tier: 2, arch: 'cross-jacks', cue: 'Focus on using your leg, chest and arm muscles to perform the jumps and' },
    { id: 'high-knees', name: 'High Knees', pool: 'sweat', groups: ['impact'], equip: [], tier: 1, arch: 'high-knees', cue: 'Lift your knees as high as possible while maintaining proper form and balance' },
    { id: 'jack-knives', name: 'Jack Knives', pool: 'sweat', groups: ['impact'], equip: [], tier: 1, arch: 'jumping-jacks', cue: 'If the full movement is too challenging, modify by bending your knees slightly' },
    { id: 'jumping-jack', name: 'Jumping Jack', pool: 'sweat', groups: ['impact'], equip: [], tier: 1, arch: 'jumping-jacks', cue: 'Maintain a slight bend in your knees throughout the exercise to absorb impact' },
    { id: 'pike-jacks-feet-kicking-in-and-out', name: 'Pike Jacks Feet Kicking in and Out', pool: 'sweat', groups: ['impact'], equip: [], tier: 1, arch: 'jumping-jacks', cue: 'Full range, land soft' },
    { id: 'running', name: 'Running', pool: 'sweat', groups: ['impact'], equip: [], tier: 1, arch: 'sprint-place', cue: 'Stay hydrated and take breaks, especially during longer runs' },
    { id: 'skater-hops', name: 'Skater Hops', pool: 'sweat', groups: ['impact', 'low'], equip: [], tier: 2, arch: 'skater-hops', cue: 'Bound side to side, stick each landing' },
    { id: 'skipping', name: 'Skipping', pool: 'sweat', groups: ['impact'], equip: [], tier: 1, arch: 'jump-rope', cue: 'Breathe steadily and rhythmically to maintain oxygen flow during the exercise' },
    { id: 'star-jump', name: 'Star Jump', pool: 'sweat', groups: ['impact'], equip: [], tier: 2, arch: 'star-jump', cue: 'Focus on using your leg muscles to generate the jump, avoiding excessive' },
    { id: 'unilateral-box-jump', name: 'Unilateral Box Jump', pool: 'sweat', groups: ['impact', 'upper'], equip: ['bench'], tier: 3, arch: 'squat-jump', cue: 'Explode up, land soft into the next one' },
    { id: 'unilateral-box-jump-bilateral-deceleration', name: 'Unilateral Box Jump - Bilateral Deceleration', pool: 'sweat', groups: ['impact', 'upper'], equip: ['bench'], tier: 3, arch: 'squat-jump', cue: 'Explode up, land soft into the next one' },
    { id: 'unilateral-jumps', name: 'Unilateral Jumps', pool: 'sweat', groups: ['impact'], equip: [], tier: 2, arch: 'jumping-jacks', cue: 'Full range, land soft' },
    { id: 'air-punches-march', name: 'Air Punches March', pool: 'sweat', groups: ['low', 'upper'], equip: [], tier: 1, arch: 'punch-overhead', cue: 'Keep your core engaged to maintain balance and stability throughout the' },
    { id: 'alternate-toe-tap-leg-lift', name: 'Alternate Toe Tap Leg Lift', pool: 'sweat', groups: ['low'], equip: [], tier: 1, arch: 'toe-taps', cue: 'Keep your core engaged throughout the exercise to maintain stability and' },
    { id: 'alternating-leg-lifts', name: 'Alternating Leg Lifts', pool: 'sweat', groups: ['low'], equip: [], tier: 1, arch: 'fast-feet', cue: 'Low stance, chop the feet as fast as you can' },
    { id: 'alternating-toe-tap', name: 'Alternating Toe Tap', pool: 'sweat', groups: ['low'], equip: [], tier: 1, arch: 'toe-taps', cue: 'Quick alternating taps, stay springy' },
    { id: 'chest-fly-side-step', name: 'Chest Fly Side Step', pool: 'sweat', groups: ['low', 'upper'], equip: [], tier: 1, arch: 'bb-bench', cue: 'Perform the movement slowly and with control to maximize muscle activation' },
    { id: 'dumbbell-swing', name: 'Dumbbell Swing', pool: 'sweat', groups: ['low'], equip: ['dumbbell'], tier: 2, arch: 'fast-feet', cue: 'Low stance, chop the feet as fast as you can' },
    { id: 'dynamic-leg-swing', name: 'Dynamic Leg Swing', pool: 'sweat', groups: ['low'], equip: [], tier: 1, arch: 'leg-swings-fb', cue: 'Keep the swinging leg straight, but avoid locking the knee to reduce strain' },
    { id: 'fast-feet', name: 'Fast Feet', pool: 'sweat', groups: ['low'], equip: [], tier: 1, arch: 'fast-feet', cue: 'Stay on your forefeet to maintain quick, light movements' },
    { id: 'heel-touches', name: 'Heel Touches', pool: 'sweat', groups: ['low'], equip: [], tier: 1, arch: 'butt-kicks', cue: 'Move slowly and with control to maximize the effectiveness of the exercise' },
    { id: 'pike-alternating-opposite-hip-taps', name: 'Pike Alternating Opposite Hip Taps', pool: 'sweat', groups: ['low'], equip: [], tier: 1, arch: 'fast-feet', cue: 'Low stance, chop the feet as fast as you can' },
    { id: 'resistance-band-pull-apart', name: 'Resistance Band Pull Apart', pool: 'sweat', groups: ['low'], equip: ['band'], tier: 2, arch: 'band-pull-apart', cue: 'Keep your arms straight throughout the exercise, maintaining a slight bend in' },
    { id: 'resistance-band-standing-external-rotation', name: 'Resistance Band Standing External Rotation', pool: 'sweat', groups: ['low'], equip: ['band'], tier: 2, arch: 'torso-twist', cue: 'Perform the movement slowly and with control to maximize muscle activation' },
    { id: 'alternate-punching', name: 'Alternate Punching', pool: 'sweat', groups: ['upper'], equip: [], tier: 1, arch: 'punch-overhead', cue: 'Keep your core engaged to maintain balance and stability throughout the' },
    { id: 'alternating-hamstring-curl-with-punch', name: 'Alternating Hamstring Curl with Punch', pool: 'sweat', groups: ['upper'], equip: [], tier: 1, arch: 'db-curl', cue: 'Focus on squeezing your hamstrings and glutes as you curl your leg to enhance' },
    { id: 'arm-pulses-palms-downwards', name: 'Arm Pulses Palms Downwards', pool: 'sweat', groups: ['upper'], equip: [], tier: 1, arch: 'dd-hold', cue: 'Engage your core to maintain stability and support your back throughout the' },
    { id: 'bodyweight-standing-triangle-fly', name: 'Bodyweight Standing Triangle Fly', pool: 'sweat', groups: ['upper'], equip: [], tier: 1, arch: 'bb-bench', cue: 'Maintain an upright posture and avoid arching your back during the exercise' },
    { id: 'boxing-jab', name: 'Boxing Jab', pool: 'sweat', groups: ['upper'], equip: [], tier: 1, arch: 'shadow-box', cue: 'Keep your non-punching hand up to protect your face and maintain a balanced' },
    { id: 'boxing-left-hook', name: 'Boxing Left Hook', pool: 'sweat', groups: ['upper'], equip: [], tier: 1, arch: 'shadow-box', cue: 'Keep your non-punching hand up to protect your face and maintain a balanced' },
    { id: 'boxing-left-uppercut', name: 'Boxing Left Uppercut', pool: 'sweat', groups: ['upper'], equip: [], tier: 1, arch: 'shadow-box', cue: 'Keep your non-punching hand up to protect your face and maintain a balanced' },
    { id: 'boxing-right-cross', name: 'Boxing Right Cross', pool: 'sweat', groups: ['upper'], equip: [], tier: 1, arch: 'shadow-box', cue: 'Keep your non-punching hand up to protect your face and maintain a balanced' },
    { id: 'criss-cross-arms-lift', name: 'Criss Cross Arms Lift', pool: 'sweat', groups: ['upper'], equip: [], tier: 1, arch: 'cross-jacks', cue: 'Focus on using your shoulder muscles to lift and lower your arms, maintaining' },
    { id: 'criss-cross-elbow-to-knee', name: 'Criss Cross Elbow to Knee', pool: 'sweat', groups: ['upper'], equip: [], tier: 1, arch: 'cross-jacks', cue: 'Focus on using your abdominal muscles to twist your torso and lift your knee' },
    { id: 'diagonal-punch', name: 'Diagonal Punch', pool: 'sweat', groups: ['upper'], equip: [], tier: 1, arch: 'punch-overhead', cue: 'Keep your hands up and elbows slightly bent when not punching to protect your' },
    { id: 'double-punch-front-leg-lift', name: 'Double Punch Front Leg Lift', pool: 'sweat', groups: ['upper'], equip: [], tier: 1, arch: 'punch-overhead', cue: 'Ensure your punches are strong and controlled, extending fully without' },
    { id: 'lying-on-side-arm-circle-warm-up', name: 'Lying on Side Arm Circle Warm Up', pool: 'sweat', groups: ['upper'], equip: [], tier: 1, arch: 'arm-circles', cue: 'Reach long, shoulders loose' },
    { id: 'pike-individual-alternating-arm-reaches', name: 'Pike Individual Alternating Arm Reaches', pool: 'sweat', groups: ['upper'], equip: [], tier: 1, arch: 'punch-overhead', cue: 'Punch the ceiling, alternate fast' },
    { id: 'pike-shoulder-taps', name: 'Pike Shoulder Taps', pool: 'sweat', groups: ['upper'], equip: [], tier: 1, arch: 'punch-overhead', cue: 'Punch the ceiling, alternate fast' },
    { id: 'resistance-band-shoulder-adduction', name: 'Resistance Band Shoulder Adduction', pool: 'sweat', groups: ['upper'], equip: ['band'], tier: 2, arch: 'punch-overhead', cue: 'Perform the movement slowly and with control to maximize muscle activation' },
    { id: 'resistance-band-standing-single-arm-shoulder', name: 'Resistance Band Standing Single Arm Shoulder Flexion', pool: 'sweat', groups: ['upper'], equip: ['band'], tier: 2, arch: 'punch-overhead', cue: 'Focus on engaging your shoulder and upper back muscles throughout the movement' },
    { id: 'shadow-boxing', name: 'Shadow Boxing', pool: 'sweat', groups: ['upper'], equip: [], tier: 1, arch: 'shadow-box', cue: 'Focus on proper form and technique with each punch to maximize effectiveness' },
    { id: 'side-to-side-punch', name: 'Side to Side Punch', pool: 'sweat', groups: ['upper'], equip: [], tier: 1, arch: 'punch-overhead', cue: 'Focus on rotating your torso to generate power in your punches while keeping' }
  ];

  /* Resolve each entry's archetype into the fields the player and tools read.
   * An entry may override cycle, alt, or props; otherwise it inherits them. */
  var EX = RAW.map(function (e) {
    var a = ARCH[e.arch] || ARCH['squat'];
    if (!e.frames) e.frames = a.frames;
    if (e.cycle == null) e.cycle = a.cycle;
    if (e.alt == null && a.alt) e.alt = true;
    if (!e.props && a.props) e.props = a.props;
    return e;
  });

  var BY_ID = {};
  for (var i = 0; i < EX.length; i++) BY_ID[EX[i].id] = EX[i];

  global.S3 = global.S3 || {};
  global.S3.exercises = { all: EX, byId: BY_ID, poses: { STAND: STAND }, arch: ARCH };
})(window);
